export const meta = {
  name: 'cart-build',
  description: 'Round-3 cart: apply the winning spec INSIDE the stock Kalles drawer and cart page — two engineers on disjoint files, one contract reviewer, one fixer',
  phases: [
    { title: 'Build', detail: 'drawer + item snippet · cart page + template' },
    { title: 'Review', detail: 'contract reviewer over the four files' },
    { title: 'Fix', detail: 'apply reviewer findings' },
  ],
}
const REPO = '/home/user/ElmsNest', THEME = `${REPO}/theme`, CART = `${REPO}/brief/side-pages/cart`, SIM = `${REPO}/brief/side-pages/simplify`, SRC = `${REPO}/brief/inventory/theme-src`

const COMMON = `You are building one half of the ElmsNest round-3 CART inside the stock Kalles theme. Read first, in this order: ${CART}/WINNING-SPEC.md (the contract — §1 table of devices, §2 acceptance numbers, §3 files), ${CART}/INVENTORY-DRAWER.md (§"The nine findings", §"The contract a rebuild must keep" — the JS contract table — and §"The no-JS cart page"), and ${SIM}/SPEC.md §2 (principles P1–P7: P1 stock Shopify patterns, P2 each question once, P4 Hebrew copy verbatim and claim-free, P6 every digit/Latin token inside a Hebrew line in <bdi dir="ltr">, P7 files stay / templates drop). The owner's verdict (${SIM}/SPEC.md §0) is binding: no invention, no decoration, the stock component in the night language.
The files you edit are VERBATIM copies of Kalles' own files (md5 identical to the dev theme) placed under ${THEME}; edit them with the Edit tool, smallest possible diffs, never rewrite. Kalles' JavaScript re-renders the drawer after every add and replaces line items on quantity change, so EVERY element, attribute, ref, name= and form id in the contract table must survive byte-for-byte: <hdt-cart-drawer id section-id ref="hdt-cart" data-count data-total-price>, <dialog id="CartDrawer" ref="dialog" pos="right" scroll-lock>, <button ref="closeButton" aria-controls="CartDrawer">, <form action=cart id method=POST> + button[name=checkout], <hdt-line-item>, <hdt-quantity-wrapp> + button[name=minus] / input[name="updates[]"][data-index] / button[name=plus], <wrapp-remove-item-oncart data-index>, <hdt-main-cart ref="hdt-cart" section-id>, <cart-items-component>. Rendered references you can read: ${CART}/mirrors/drawer-full/index.html and ${CART}/mirrors/cart-full/index.html (the mirrors also hold hdt-cart-drawer.css / hdt-main-cart.css under their assets dir — grep them for the class you are about to change), the screenshots ${CART}/shots/*.png, and Kalles' read-only helpers in ${SRC}/snippets/ (line-item-price.liquid takes get_total: true; item-cart-page.liquid is the cart page's per-line snippet and already carries ONE outer remove link at its lines 63-68 — do not edit it). The acceptance harness ${CART}/verify.js says exactly what is measured (read its header comment); you cannot run it (measurement needs a deploy), so reason from the markup.
Hard rules: valid Liquid (balanced tags, only filters Kalles uses); no sequence of three double quotes anywhere; Hebrew copy exactly as given here (guillemets «» are notation, never typed); no new sentences of your own beyond the words this brief licenses; no WhatsApp, no counts of sales/reviews, no urgency; the skin ${THEME}/snippets/elmsnest-s-skin.liquid and ${THEME}/snippets/elmsnest-s-pdp-terms-line.liquid and ${THEME}/snippets/elmsnest-v2-core.liquid are READ-ONLY for you — when a skin rule must change, return the exact replacement rule in skinPatch (selector as it appears in the skin, the full new declaration block, and the current line number) and the lead applies it. The four collections in menu order are the ones in ${THEME}/templates/index.json → ens_collections block_order (handles: תאורת-שביל-סולארית, solar-wall-lights, ספוטים-ופרוז-קטורים-סולאריים, גרילנדות-ותאורה-דקורטיבית); render them with collections[handle].title and .url and data-ens-place="<handle>". When done, run 'python3 ${REPO}/brief/lint.py ${THEME}' and fix anything it reports in YOUR files; report the rest.`

const BUILD_SCHEMA = { type: 'object', required: ['files', 'skinPatch', 'assumptions', 'deviations', 'lint'], properties: {
  files: { type: 'array', items: { type: 'object', required: ['path', 'edits'], properties: { path: { type: 'string' }, edits: { type: 'array', items: { type: 'string' } } } } },
  skinPatch: { type: 'array', items: { type: 'object', required: ['line', 'selector', 'newRule', 'why'], properties: { line: { type: 'number' }, selector: { type: 'string' }, newRule: { type: 'string' }, why: { type: 'string' } } } },
  assumptions: { type: 'array', items: { type: 'string' } },
  deviations: { type: 'array', items: { type: 'string' } },
  lint: { type: 'string' },
} }

const ENGINEERS = [
  { key: 'drawer', prompt: `${COMMON}
YOUR FILES: ${THEME}/sections/cart-drawer.liquid (1187 lines: form_id 'CartDrawer-Form' at line 3; cart_items assigned at 15-18; the drawer exists only when request.page_type != 'cart' (line 27); header <h3 class="hdt-mini-cart__header-title"> line 32; empty state 44-53; items form + loop 56-60; bottom blocks 111-175 — subtotal, tax, agree, btn_cart (the view-cart <a>, ~line 160), btn_checkout (~line 169); schema from 303) and ${THEME}/snippets/item-cart.liquid (103 lines: title <a> line 35 with class hdt-truncate; variant line 36; price line 37 = render 'line-item-price'; stepper 66-82 with the inner <wrapp-remove-item-oncart> at 70-73 shown in place of the minus icon when item.quantity == 1 and a style="top: 5px" hack on the minus button; the outer <wrapp-remove-item-oncart> at 84-89 stays).
Apply exactly these devices from WINNING-SPEC §1, nothing more:
D1 Header count: the h3 keeps its classes and 'sections.cart.title' | t; when cart_items != empty append « · <bdi dir="ltr">N</bdi> פריטים» where N = cart.item_count | minus: has_protect_product, and «פריט אחד» (no digit) when N == 1. Nothing when empty.
D2 View-cart demoted: in the btn_cart block keep <a href="{{ routes.cart_url }}" data-no-instant …> with class hdt-mini-cart__btn-viewcart but drop every button class (hdt-button-block hdt-btn hdt-font-semibold hdt-btn-full-width, the block style/size classes) and any inline style from the block settings; add the class env2-link (it exists in elmsnest-v2-core: inline-flex text link with a hairline underline). Keep the icon branch and the translated label. The checkout <button> must end up the ONLY .hdt-btn in .hdt-mini-cart__bottom. skinPatch must then replace the skin's two rules for .hdt-mini-cart__btn-viewcart.hdt-btn (lines 106-107) with rules for #CartDrawer .hdt-mini-cart__btn-viewcart (a centred text link, 44 px min tap height via padding, ink-2 colour, glow on hover, no border-radius pill, no letter-spacing) — write them out in full.
D3 Terms line above the subtotal: inside <div class="hdt-mini-cart__bottom-wrap"> BEFORE the {%- for block in section.blocks -%} loop insert <div class="ens-cart-terms">{%- render 'elmsnest-s-pdp-terms-line' -%}</div> (no product passed, so the snippet's sticky-sync script does not render; its <p class="ens-terms-line"> and <style> do). Do not edit the snippet. The item list must no longer flex to fill the drawer: find in the mirror's hdt-cart-drawer.css which rule stretches .hdt-mini-cart__main / .hdt-mini-cart__sroll (flex:1 / flex-grow) and return a skinPatch rule under #CartDrawer that sets it to flex:0 1 auto so the bottom block rises to meet the last line (void ≤ 40 px at 390×844 is the target); the scroll area must still scroll when there are many lines (max-block-size with overflow:auto).
D4 Full name: remove hdt-truncate from the title <a> (line 35). skinPatch: the skin's .hdt-mini-cart__title rule (line 97) drops display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical and keeps the rest (white-space:normal, serif 700 16px, line-height 1.3, ink).
D5 Variant promoted: line 36 keeps its element and classes; skinPatch: the skin's line-98 rule currently lists .hdt-mini-cart__meta-variant with .hdt-text-secondary and .hdt-cart-tax in ink-2 — split it so .hdt-mini-cart__meta-variant becomes color:var(--env2-gold);font-size:13px;line-height:1.4;margin-block-start:2px and the other two stay ink-2.
D6 Line total when quantity > 1: replace line 37 with: if item.quantity > 1 → <div class="hdt-mini-cart__price">{%- render 'line-item-price', line_item: item, price_class: 'hdt-price-wrapp', get_total: true -%}</div><div class="hdt-mini-cart__unit hdt-text-secondary"><span class="hdt-money">{{ item.final_price | money }}</span> ליחידה</div>, else the current single-unit render unchanged. skinPatch: a rule #CartDrawer .hdt-mini-cart__unit{font-family:var(--env2-sans);font-size:12px;line-height:1.4;color:var(--env2-ink-2)} (add after line 99).
D7 One remove control: at item.quantity == 1 the minus button keeps name="minus" type="button" and its classes, gains disabled and aria-disabled="true", and renders the minus icon ({%- render 'icon' with 'minus' -%}) instead of the inner <wrapp-remove-item-oncart>; delete the style="top: 5px" hack. The outer remove at 84-89 is the one bin. Check in the mirror's JS-facing markup that Kalles' stepper does not require the inner element (grep the mirror index.html and hdt-cart-drawer.css for 'wrapp-remove-item-oncart' and 'is--minus').
D8 Empty drawer: keep the <p>{{ 'sections.cart.empty' | t }}</p>; delete the svg and the settings.empty_cart_link button; add <nav class="ens-cart-empty" aria-label="קולקציות"> with the four collection links in menu order (see COMMON), each <a class="env2-link" href="{{ c.url }}" data-ens-place="{{ h }}">{{ c.title | escape }}</a>, one per line (skinPatch: #CartDrawer .ens-cart-empty{display:grid;gap:14px;justify-items:center;margin-block-start:18px}). Nothing else in the empty state.
Do NOT change: data-count / data-total-price, the form and its hidden input, the subtotal/tax/agree blocks, the checkout button's markup, the schema. Report every line you touched in files[].edits as 'L<n>: what'.` },
  { key: 'page', prompt: `${COMMON}
YOUR FILES: ${THEME}/sections/main-cart.liquid (1150 lines: form_id 'CartPage-Form' line 2; {% style %} block 27-29; <hdt-main-cart ref="hdt-cart"> line ~30 wrapping <div class="hdt-container">; empty branch 31-66 (svg + h3 'sections.cart.empty' + empty_html text + settings.empty_cart_link button + optional shipping bar); items branch 68-119 = a <table class="hdt-cart-items"> whose rows render 'item-cart-page' (line 95, read-only snippet with the outer remove link) and a stepper at 99-110 where at item.quantity == 1 an inner <wrapp-remove-item-oncart> is shown (line ~100) and the minus button gets hdt-hidden (line ~101); footer <div class="hdt-page-cart__footer"> from line 121 with two columns, the blocks loop (subtotal, tax, agree, btn_checkout ~229-256, accelerated_btns, img_trust, payment-terms) in the second column from line 184; schema from 341 — read the btn_checkout block schema (~469) for any full-width or size setting) and ${THEME}/templates/cart.json (drop two sections).
Apply exactly these, nothing more:
C1 Template: remove main_heading_zHKQUU and elmsnest_cart_guidance from "sections" AND "order" (P7: the section files stay on the theme). Keep every main-cart block and setting as is, except where C5 says. Re-parse the JSON after stripping the /* */ header (node -e or python3 -c).
C2 Checkout inside the fold at 360×640: on phones the whole footer (subtotal · terms line · checkout) must come BEFORE the item table. Use CSS only, in the section's existing {% style %} block: @media (max-width:767px){ hdt-main-cart .hdt-container{display:flex;flex-direction:column} hdt-main-cart .hdt-page-cart__footer{order:-1} } — first confirm in the mirror's hdt-main-cart.css that .hdt-container / .hdt-page-cart__footer carry no display or float rule that this would break, and that the empty branch is unaffected (it has no footer). Desktop order stays stock.
C3 Terms line: in the footer's second column, immediately BEFORE the {%- if section.blocks.size > 0 -%} block, insert <div class="ens-cart-terms">{%- render 'elmsnest-s-pdp-terms-line' -%}</div> (no product passed → no script). The three guidance boxes are gone with C1; nothing else says terms on the page.
C4 No-JS quantity: inside <hdt-quantity-wrapp>, right after the <input name="updates[]">, add <noscript> with plain links beside the number — a minus link to {{ routes.cart_change_url }}?line={{ item.index | plus: 1 }}&quantity={{ item.quantity | minus: 1 }} only when item.quantity > 1 (at 1 the outer remove link already is the way out), and a plus link to …&quantity={{ item.quantity | plus: 1 }} unless max_qty is set and item.quantity >= max_qty; visible glyphs − and +, each with aria-label «פחות» / «יותר» and class ens-cart-qtylink. Keep the JS buttons (name=minus / name=plus, no-js-hidden) verbatim.
C5 One remove control per line: delete the stepper's inner <wrapp-remove-item-oncart> (~line 100); the minus button loses its conditional hdt-hidden and instead gains disabled and aria-disabled="true" when item.quantity == 1. The outer remove in item-cart-page stays (do not edit that snippet).
C6 Empty page: keep the <h3>{{ 'sections.cart.empty' | t }}</h3> (drop hdt-uppercase and hdt-text-12xl, keep hdt-page-cart__emty-heading hdt-font-semibold); delete the svg, the empty_html text div and the settings.empty_cart_link button; add the same four-collection <nav class="ens-cart-empty" aria-label="קולקציות"> as the drawer (see COMMON; class env2-link on each link, data-ens-place). Keep the form and the optional shipping bar block as they are.
C7 The checkout button: read the btn_checkout block schema; if a full-width setting exists set it in the template; otherwise return a skinPatch rule for .hdt-main-cart__button-checkout that makes it full width of its column with min-height:52px, the gold fill and btn-ink colour exactly as the skin's line 104 drawer checkout rule, and no letter-spacing. The button must remain <button form="{{ form_id }}" type="submit" name="checkout"> unchanged.
Report every line you touched in files[].edits as 'L<n>: what'.` },
]

phase('Build')
const built = await parallel(ENGINEERS.map(e => () => agent(e.prompt, { label: `build:${e.key}`, phase: 'Build', schema: BUILD_SCHEMA, effort: 'high' }).then(r => ({ key: e.key, r }))))
const ok = built.filter(Boolean)
log(`built: ${ok.map(b => b.key).join(', ')}; skin patches: ${ok.reduce((n, b) => n + (b.r.skinPatch || []).length, 0)}`)

phase('Review')
const REVIEW_SCHEMA = { type: 'object', required: ['verdict', 'findings'], properties: {
  verdict: { type: 'string' },
  findings: { type: 'array', items: { type: 'object', required: ['file', 'line', 'severity', 'problem', 'fix'], properties: { file: { type: 'string' }, line: { type: 'integer' }, severity: { type: 'string', description: 'blocker | high | medium | low' }, problem: { type: 'string' }, fix: { type: 'string' } } } },
} }
const review = await agent(`You are the contract reviewer for the ElmsNest round-3 CART build. Read ${CART}/WINNING-SPEC.md, the contract table and the no-JS section of ${CART}/INVENTORY-DRAWER.md, and ${SIM}/SPEC.md §0–§2. Then diff each edited file against its verbatim Kalles original: ${THEME}/sections/cart-drawer.liquid vs ${SRC}/sections/cart-drawer.liquid, ${THEME}/snippets/item-cart.liquid vs ${SRC}/snippets/item-cart.liquid, ${THEME}/sections/main-cart.liquid vs ${SRC}/sections/main-cart.liquid (run 'diff -u' in Bash and read every hunk), and ${THEME}/templates/cart.json (parse it after stripping the /* */ header). The engineers' own reports: ${JSON.stringify(ok.map(b => ({ key: b.key, files: b.r.files, skinPatch: b.r.skinPatch, assumptions: b.r.assumptions, deviations: b.r.deviations, lint: b.r.lint })))}.
Check and report as findings (file, line, severity, problem, fix): (1) every element/attribute of the JS contract table survives byte-for-byte in both surfaces — list any that changed; (2) Liquid validity of every hunk (balanced tags, filters Kalles uses, render names and parameter names that exist — ${SRC}/snippets/line-item-price.liquid takes get_total); (3) no sequence of three double quotes; (4) exactly one remove control per line at quantity 1 AND at quantity 2 on each surface (count <wrapp-remove-item-oncart> renders per line, including the read-only item-cart-page snippet on the page); (5) the line total renders only when quantity > 1 and the unit line under it; (6) the title <a> has no hdt-truncate; (7) the terms line renders exactly once per surface via render 'elmsnest-s-pdp-terms-line' with no product passed and inside <div class="ens-cart-terms">; (8) the empty state on each surface is the heading plus the four collection links in the index.json ens_collections order with data-ens-place, and nothing else; (9) the no-JS links: correct cart_change_url, line index (item.index | plus: 1), quantity ±1, minus omitted at 1, plus omitted at max, inside <noscript>, JS buttons untouched; (10) the checkout <button> is the only .hdt-btn in the drawer's bottom block and is unchanged in markup on both surfaces; (11) the mobile reorder CSS is in the section's {% style %} block, scoped to hdt-main-cart, and cannot affect the empty branch; (12) Hebrew copy: only «פריט אחד», «פריטים», «ליחידה», «פחות», «יותר», «קולקציות» were added, every digit inside a Hebrew run is in <bdi dir="ltr">, no claim, no WhatsApp; (13) cart.json keeps every main-cart block and setting except what C1/C7 change and drops the two sections from both "sections" and "order"; (14) the skinPatch entries name selectors that exist in ${THEME}/snippets/elmsnest-s-skin.liquid at the lines they cite (read-only; do not edit it) and the new rules are complete CSS. Severity: blocker = breaks Kalles JS / invalid Liquid or JSON / a contract element changed; high = a §1 device missing or wrong; medium = rule deviation; low = style. Do not modify files. Return a 4–8 sentence verdict.`, { label: 'review:contract', phase: 'Review', schema: REVIEW_SCHEMA, effort: 'high' })
log(`review: ${review ? review.findings.length : 'null'} findings`)

phase('Fix')
const FIXED = { type: 'object', required: ['changed', 'skipped', 'lint'], properties: { changed: { type: 'array', items: { type: 'string' } }, skipped: { type: 'array', items: { type: 'object', required: ['finding', 'reason'], properties: { finding: { type: 'string' }, reason: { type: 'string' } } } }, lint: { type: 'string' } } }
let fixed = null
if (review && review.findings.length) {
  fixed = await agent(`${COMMON}
You are the fixer. Apply EVERY finding below to the four cart files under ${THEME} with the smallest edit (Edit tool). Never touch the skin, the terms-line snippet, elmsnest-v2-core or any file outside sections/cart-drawer.liquid, snippets/item-cart.liquid, sections/main-cart.liquid, templates/cart.json. After each edit re-read the region; re-parse cart.json after stripping the header. Findings: ${JSON.stringify(review.findings)}. Then run 'python3 ${REPO}/brief/lint.py ${THEME}' and paste its last 6 lines into lint. Return the files changed and every finding you did not apply with the reason.`, { label: 'fix:apply', phase: 'Fix', schema: FIXED, effort: 'high' })
}
return { built: ok.map(b => ({ key: b.key, files: b.r.files, skinPatch: b.r.skinPatch, assumptions: b.r.assumptions, deviations: b.r.deviations, lint: b.r.lint })), review, fixed }
