export const meta = {
  name: 'collection-build-round-2',
  description: 'Build the collection plumbing and its seven sections from the collection WINNING-SPEC, each proved with an offline render',
  phases: [{ title: 'Plumbing', detail: 'ground, axis parser, rail, paginate, glyph + additive card/image edits' }, { title: 'Sections', detail: 'one engineer per section' }],
}
const ROOT = '/home/user/ElmsNest'
const DIR = `${ROOT}/brief/side-pages/collection`
const COMMON = `Repo ${ROOT} (branch claude/design-sidebar-pages-3991tn). Shopify DEV theme gid://shopify/OnlineStoreTheme/154726400174 — UNPUBLISHED; the MAIN theme is blocked and must never be targeted; NEVER publish; never change a product, collection, page or metafield.
Read before anything: ${DIR}/WINNING-SPEC.md (binding), ${DIR}/BRIEF.md, ${ROOT}/brief/WINNING-SPEC.md §3 (the homepage design system), ${ROOT}/brief/build-preview/CONTRACT.md, ${ROOT}/brief/side-pages/pdp/WINNING-SPEC.md §3.5/§3.6/§4.8 (image ledger, option-axis rule, the product card you REUSE), ${ROOT}/brief/side-pages/core/REPORT.md §9 (known core bugs you must not inherit), ${ROOT}/brief/side-pages/OWNER-NOTES.md, ${ROOT}/brief/DEPLOY.md.
Data: ${DIR}/data.json (five collections, 27 products, the first option axis with a price per value, image URLs) and ${ROOT}/brief/side-pages/pdp/products.json (full description text). Metafields are EMPTY on 26 of 27 products — never depend on one.
Facts that constrain everything: the shared core (snippets/elmsnest-v2-core.liquid) is rendered from layout/theme.liquid on every page and provides the tokens, Frank Ruhl Libre + Heebo, .env2-* helpers, [data-lamp], window.env2, the pill buttons and the night ground — do not re-render it, do not redefine its tokens, do not edit it this round. Because of core REPORT §9.1 every primary call to action must be a <button> inside a form or set its own colour explicitly (an <a class="env2-btn"> renders ink-on-glow at 1.21:1). Never use --en-warning-text / -success- / -error- / -info- (cream-era). No sales: no badge, no strikethrough, no "-N%". No WhatsApp label. Latin tokens and prices in <bdi>. Logical CSS properties only. No Liquid inside {% stylesheet %} / {% javascript %}. Schema name max 25 chars. No three consecutive double-quotes in any file. Radius 0 except pills.
Tooling: offline previews only in this phase — node ${ROOT}/brief/shot.js <file> <prefix> renders at 1440 and 390 and prints heights, horizontal overflow and JS errors. Playwright is at /tmp/claude-0/-home-user-ElmsNest/1c2132db-077d-58e0-b54a-35f2ebea6b2c/scratchpad/node_modules/playwright, chromium /opt/pw-browsers/chromium-1194/chrome-linux/chrome (--no-sandbox). Do not deploy — a later integrator does that. Do not commit with git. Do not use gh.
**This container is restarted every hour or two. Write every artefact to disk as soon as it exists and never hold work in memory across steps; if files from an interrupted earlier run of you are already on disk, read them, keep what is good and finish only what is missing.**`
const FILE_SCHEMA = { type: 'object', required: ['files', 'preview', 'lint', 'notes'], properties: { files: { type: 'array', items: { type: 'string' } }, preview: { type: 'array', items: { type: 'string' } }, lint: { type: 'string' }, schemaIds: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' }, risks: { type: 'array', items: { type: 'string' } } } }

phase('Plumbing')
const plumbing = await agent(`${COMMON}

You are the plumbing engineer for the collection build. Build ONLY the shared pieces, in ${ROOT}/theme/ (repo paths mirror theme paths). Do NOT build any section.
Per WINNING-SPEC §5.2 and §5.3:
1. snippets/elmsnest-v2-ground-collection.liquid — §3.1, mirroring snippets/elmsnest-v2-ground-product.liquid (read it first); scoped to body.hdt-page-type-collection so it cannot touch another template. It must work for a page that is one screen (6 products) or five screens (27).
2. snippets/elmsnest-v2-coll-axis.liquid — parses options_with_values[0] into {value, number, unit, price, variant_id, available} — the single source of every number on this page. It must handle the real Hebrew values in data.json: "5 מ׳ / 20 נורות", "12×2 מ׳ / 780 LED", "2 יחידות", "4 יח׳", "6W", "3000K", "72 LED / 100W", and values with no number at all. Emit both Liquid variables and one JSON script tag.
3. snippets/elmsnest-v2-coll-rail.liquid — one product's dot rail with its three stop states (below reach / at reach / beyond reach), per §4.2.
4. snippets/elmsnest-v2-coll-paginate.liquid — §3.7: renders only when paginate.pages > 1 and carries sort_by through.
5. snippets/elmsnest-v2-coll-glyph.liquid — §3.6.3: the five-glyph sprite plus the «איור · אין תצלום נקי» plate for the 15 products with no clean photograph.
6. **Additive edits, never forks:** snippets/elmsnest-v2-pdp-card.liquid gets the three optional params of §3.5, and snippets/elmsnest-v2-pdp-image.liquid gets the env2_no_clean_image handle list and the glyph branch of §3.6.2 — SAME signature. After editing the card you must prove the product page still renders it identically: render the PDP related row markup both ways in a local HTML and diff the two; state the result.
Also extend ${ROOT}/brief/lint.py to glob sections/elmsnest-v2-coll-* and snippets/elmsnest-v2-coll-* and to validate templates/collection.json against the new schemas, keeping its existing checks.
Prove it: build ${DIR}/build-preview/_plumbing.html rendering the axis parse for all 27 products (a table: handle → parsed stops with numbers, units and prices — this is the file that proves the parser), the rail in its three states, the glyph plate, and the card in its new modes; screenshot with node ${ROOT}/brief/shot.js and READ the PNG. Run python3 ${ROOT}/brief/lint.py until it passes.
Write ${DIR}/build-preview/CONTRACT-COLL.md: each snippet's exact call signature, inputs, what it prints, the class names it emits and the JSON shape — the seven section engineers build against this document, so make it precise and final.
Return files, preview paths, lint result, and the risks a section engineer must know.`, { label: 'plumbing', phase: 'Plumbing', schema: FILE_SCHEMA, effort: 'high' })
if (!plumbing) return { error: 'plumbing failed' }
log(`plumbing: ${plumbing.files.length} files, lint ${plumbing.lint}`)

phase('Sections')
const SECTIONS = [
  { id: 'scene', spec: '4.1', title: 'the gate — first screen', note: 'Renders snippets/elmsnest-v2-ground-collection (the only section that does). The first screen must carry, on 1440x900 AND 390x844: where you are (collection title as a real <h1> in the serif over a full-bleed night photograph), the approved suits/does-not-suit phrase for that place, the count and price span from Liquid, and ONE pinned product — a lit dot, a hairline stem, a gold tag — with its real price and a route to buy. This is the fix for the audit\'s worst defect (no price and no product in the fold on four of five URLs).' },
  { id: 'ruler', spec: '4.2', title: 'the instrument — the narrowing device', note: 'The graft from the "howmuch" concept and the spine of the page: size radios (metres / points of light / watts, per collection) that collapse every product row to ONE real price at the chosen value, dim what cannot reach it and print its maximum instead of hiding it. **The state must live in the URL and work with JavaScript disabled** (plain <a> links, server-side), with JS only enhancing. Plus the sort line: plain ?sort_by= links, no toolbar, no drawer, no density selector.' },
  { id: 'bands', spec: '4.3', title: 'the walk — five compositions', note: 'The products as stations of one evening, each band composed differently (never a repeating grid). Uses the card via the plumbing contract with the new params. Every product of the collection must appear exactly once across the bands, whatever the collection size (6, 7, 8 or 27).' },
  { id: 'span', spec: '4.4', title: 'the fourteen-times screen', note: 'Only for collections whose price span needs explaining (path 69.90-999.90). Carries an enabled checkbox and renders NOTHING when off. Must state honestly WHY the expensive one costs more (it is a set of 8 units, not a better lamp) and show the derived per-unit price.' },
  { id: 'ledger', spec: '4.5', title: 'the measure table', note: 'The table that answers "I have a six-metre pergola" in one row, with every price. Enabled checkbox. Built entirely from the axis parser — no typed numbers.' },
  { id: 'terms', spec: '4.6', title: 'the four numbers', note: 'The licensed consumer wording, compact. Same facts as the PDP and the homepage; no new claim.' },
  { id: 'goodnight', spec: '4.7', title: 'the way out', note: 'Where the visitor goes next: the other places, the whole catalogue, and the small step (the mailto photo CTA via snippets/elmsnest-v2-pdp-photo-cta.liquid). No newsletter, nothing fixed bottom-left.' },
]
const built = await parallel(SECTIONS.map(s => () => agent(`${COMMON}

You are the engineer for ONE collection section: **sections/elmsnest-v2-coll-${s.id}.liquid** (WINNING-SPEC §${s.spec} — ${s.title}).
The plumbing is built and its contract is ${DIR}/build-preview/CONTRACT-COLL.md — READ IT FIRST and build against it; the snippets exist in ${ROOT}/theme/snippets/. Plumbing notes: ${plumbing.notes} ${(plumbing.risks || []).join(' · ')}
Section-specific: ${s.note}
Write ${ROOT}/theme/sections/elmsnest-v2-coll-${s.id}.liquid: markup + {% stylesheet %} (every selector prefixed .env2-coll-${s.id}__…) + {% javascript %} (init via document.querySelectorAll('[data-env2-coll-${s.id}]'), ending with the CONTRACT's env2.observe fallback) + {% schema %} with settings, blocks and ONE preset. Root: <section id="env2-coll-${s.id}" data-env2-coll-${s.id} class="env2-section env2-coll" dir="rtl" style="scroll-margin-top:90px">. Every block root carries {{ block.shopify_attributes }}. Copy exactly as §${s.spec} specifies; every number from Liquid (collection.products_count, the axis parser, prices), never typed.
It must render correctly for ALL FIVE URLs: decor (7 products, 105 variants, every product a range), path (8 products, 69.90–999.90, a 14x span), wall (6, narrow span, no shared unit), spot (6, no shared unit, and almost every image is a marketing poster so the glyph branch fires), and all (27, mixed units). Guard every axis, every image index, every empty field.
Prove it offline before returning: build ${DIR}/build-preview/${s.id}.html — your section's rendered markup for the DECOR collection (hand-substitute the Liquid you wrote) on the page ground with local assets and fonts, plus ${DIR}/build-preview/${s.id}-path.html for the path collection if your section behaves differently there. Screenshot each with node ${ROOT}/brief/shot.js, READ the PNGs, and fix what they show (overflow, clipped text, contrast, tap targets ≥44px, mobile composition) until they are right. Run python3 ${ROOT}/brief/lint.py and fix anything about your file.
No-JS and reduced-motion: the section must render fully and buyably with JS disabled — for the ruler that means the size choice is a link, not a script. State exactly what degrades.
Return the file, the preview paths, lint result, your schema setting ids, notes, and the risks the integrator must check on the real render.`, { label: `section:${s.id}`, phase: 'Sections', schema: FILE_SCHEMA, effort: 'high' })))
const sok = built.filter(Boolean)
log(`sections built: ${sok.length}/7`)
return { plumbing, sections: sok.map(s => ({ files: s.files, schemaIds: s.schemaIds, risks: s.risks, notes: s.notes })) }
