export const meta = {
  name: 'dropship-sweep',
  description: 'Sweep every surface of the ElmsNest store for text that says or implies the goods ship from abroad or that the shop is a dropshipper, and produce one table of exact locations with replacements and who can change each',
  phases: [
    { title: 'Sweep', detail: 'five surfaces read in parallel: theme, products, pages and policies, rendered pages, implication lens' },
    { title: 'Plan', detail: 'one table: location, exact text, why, replacement, who can change it' },
  ],
}
const REPO = '/home/user/ElmsNest', T = 'gid://shopify/OnlineStoreTheme/154726400174'
const MCP = 'Load the Shopify MCP tools first with ToolSearch "select:mcp__Shopify__graphql_query,mcp__Shopify__search_products,mcp__Shopify__get-product". READ ONLY: never call a mutation, never change a product, collection, page, metafield or theme file. If a GraphQL result is too large the tool saves it to a file — parse that file with python3.'
const SIGNALS = `What counts as a hit, in three tiers:
A) EXPLICIT — says the goods come from outside Israel or from a third party: «ממחסן/ממחסנים מחוץ לישראל», «משלוח בינלאומי», «יבוא», «מכס», «מהספק», «ישירות מהספק», «חו״ל», any mention of China / Shenzhen / AliExpress / a foreign supplier, an English or Chinese sentence left inside a Hebrew description, a foreign address.
B) STRUCTURAL TELL — the standard dropshipping fingerprint even without naming abroad: a long transit window (7–14 business days, 8–17 total) presented as normal, «הזמנה עם כמה פריטים עשויה להגיע בחבילות נפרדות» (split parcels), tracking that «may take days to update», «זמן ההובלה משוער» hedging, «ייתכן» about how an order ships, disclaimers about delays outside the shop's control.
C) SOFT TELL — a photograph or file with foreign packaging, foreign text baked into an image, a supplier's model number as a product title, a spec table pasted from a supplier, «דגם» codes, or copy written as if the shop never holds the item.
The owner states the truth is: the shop HAS ITS OWN WAREHOUSES IN ISRAEL and every order ships from them. So any text implying otherwise is factually wrong and must be found.`
phase('Sweep')
const HIT = { type: 'object', required: ['hits', 'notes'], properties: { notes: { type: 'string' }, hits: { type: 'array', items: { type: 'object', required: ['where', 'text', 'tier', 'why'], properties: { where: { type: 'string' }, text: { type: 'string' }, tier: { type: 'string' }, why: { type: 'string' }, surface: { type: 'string' } } } } } }
const SURFACES = [
  ['theme', `Repo ${REPO}. Read EVERY file under ${REPO}/theme (sections, snippets, layout, templates, config, locales — not assets) and find every string a customer can read that falls in tiers A, B or C. Include schema defaults and presets (they render when a block is added), Hebrew comments only if they carry customer text. Note which files are LIVE on the current pages (the S family: elmsnest-s-*.liquid, elmsnest-v2-core, layout/theme.liquid, the templates in use) and which are legacy v2 sections not in any template's order — read ${REPO}/theme/templates/*.json and sections/*-group.json to decide. For each hit give the file:line, the exact string, the tier and why.`],
  ['products', `${MCP} List ALL products of the shop (there are about 27) with title, handle, descriptionHtml, productType, vendor, tags, and every metafield in the custom namespace, plus each product's media alt texts. Use graphql_query with products(first: 50) { nodes { id title handle productType vendor tags descriptionHtml metafields(first: 30) { nodes { namespace key value } } media(first: 12) { nodes { alt } } } }. Save the result to a file if it is large and parse it with python3. Then find every string in tiers A, B or C. ${SIGNALS} Report the product handle and the exact sentence for each hit.`],
  ['pages', `${MCP} Read (a) every Shopify PAGE: pages(first: 30) { nodes { id title handle body } }; (b) the shop's policies: shop { shippingPolicy { body } refundPolicy { body } termsOfService { body } privacyPolicy { body } }; (c) every COLLECTION's description: collections(first: 30) { nodes { handle title descriptionHtml } }; (d) shop { name description } and any shop-level metafields you can read. Find every string in tiers A, B or C. ${SIGNALS} Quote the exact sentence and say which document it is in. The POLICIES matter most — they are the legally binding text.`],
  ['rendered', `Repo ${REPO}. Read the mirrored HTML of the real rendered pages — ${REPO}/brief/side-pages/pages/verify/mirrors/*/index.html (the seven content pages), ${REPO}/brief/side-pages/pdp3/verify/mirrors/*/index.html (five product pages), ${REPO}/brief/side-pages/simplify/verify-after/mirrors/*/index.html and ${REPO}/brief/inventory/*/index.html (home, collections, cart, 404, account) if present. Strip the tags with python3 and search the visible text for tiers A, B and C. This catches strings that come from Shopify data or from Kalles stock translations rather than from our own files. For each hit give the page, the exact sentence, and where in the page it sits (which section id or class).`],
  ['implication', `Repo ${REPO}. You are the suspicious-customer lens. An Israeli shopper decides in seconds whether a store is a real local shop or a foreign dropshipper. Read the rendered pages listed in ${REPO}/brief/side-pages/pages/verify/ and ${REPO}/brief/side-pages/pdp3/verify/ (the -m-js-full.png screenshots AND the mirrors' HTML) and list everything that makes the store READ as a dropshipper even where no sentence says it: the delivery window and how it is framed, split-parcel language, hedging words, missing local signals (no Israeli address, no phone, no business number, no local pickup point named), product photographs that look like supplier catalogue frames, model-number titles, spec tables in a supplier's voice, English left in a Hebrew page. ${SIGNALS} Rank what a real shopper would notice first.`],
]
const swept = await parallel(SURFACES.map(([name, task]) => () => agent(`${task}\n${name === 'theme' || name === 'rendered' || name === 'implication' ? SIGNALS : ''}\nReturn every hit with where / exact text / tier (A|B|C) / why, and notes on anything you could not read. Do not modify or write any file except a scratch file under /tmp/claude-0/-home-user-ElmsNest/1c2132db-077d-58e0-b54a-35f2ebea6b2c/scratchpad/. Never call a Shopify mutation.`, { label: `sweep:${name}`, phase: 'Sweep', schema: HIT, effort: 'high' })))
const hits = swept.filter(Boolean).flatMap(s => s.hits)
log(`${hits.length} hits across ${swept.filter(Boolean).length} surfaces`)

phase('Plan')
const PLAN = { type: 'object', required: ['rows', 'questions', 'summary'], properties: { summary: { type: 'string' }, questions: { type: 'array', items: { type: 'string' } }, rows: { type: 'array', items: { type: 'object', required: ['where', 'text', 'action', 'replacement', 'owner', 'risk'], properties: { where: { type: 'string' }, text: { type: 'string' }, action: { type: 'string' }, replacement: { type: 'string' }, owner: { type: 'string' }, risk: { type: 'string' }, tier: { type: 'string' } } } } } }
const plan = await agent(`Repo ${REPO}. You are the lead's editor. The store owner states — and it is the fact to work from — that **ElmsNest holds its own warehouses in Israel and every order ships from them**, not from abroad. The store's text currently contradicts this in places. Here is every hit five sweeps found:\n${JSON.stringify(hits).slice(0, 60000)}\n\nProduce ONE de-duplicated table. For each row: "where" (file:line or the Shopify object), "text" (the exact string as it exists), "tier", "action" (delete | rewrite | keep-but-flag), "replacement" (the exact Hebrew to put in its place — short, in the store's voice, claim-free; when a sentence exists only to explain a foreign warehouse, the action is delete, not a substitute claim), "owner" (**theme** = we can change it in the dev theme, or **shopify** = only the owner can, because it lives in a product, page, collection or policy and editing it changes the LIVE store), and "risk" (what breaks if this changes — above all: where a change would make the site contradict the binding shipping or refund POLICY, which must be updated by the owner first).
Rules for replacements: never invent a delivery time, a warehouse city, a stock figure or any claim the owner has not stated. Where a number depends on the new reality (transit 7–14 days, total 8–17 days, split parcels), do NOT choose a number — put the row in "questions" as a question for the owner instead, with the options. Keep the honesty rules of ${REPO}/brief/BRIEF.md §3 and the copy discipline of ${REPO}/brief/side-pages/simplify/SPEC.md §2.
Also read ${REPO}/brief/side-pages/pages/COPY-SOURCE.md so you know which sentences came from the owner's own pages rather than from us.
Return the rows sorted so the most visible customer-facing strings come first, the questions for the owner, and a two-sentence summary of how bad the problem is.`, { label: 'plan', phase: 'Plan', schema: PLAN, effort: 'high' })
return { hits, plan }
