export const meta = {
  name: 'home2-images',
  description: 'Source niche photographs for the home round 2: sweep Openverse + Wikimedia Commons + the store\'s own product frames, rate every candidate visually, shortlist with roles',
  phases: [
    { title: 'Gather', detail: 'three sources in parallel' },
    { title: 'Rate', detail: 'every candidate looked at, scored on the rubric' },
    { title: 'Shortlist', detail: 'merge, dedupe, roles, contact sheet' },
  ],
}
const REPO = '/home/user/ElmsNest', H = `${REPO}/brief/side-pages/home2`, IMG = `${H}/images`
const RUBRIC = `Rubric (0-5 each): atmosphere (dusk/night, warm light, calm — the store's night language); relevance (solar outdoor lighting for a garden, path, wall, balcony or terrace — a lit garden or path at night scores high, a Christmas street or a stadium scores 0); cleanliness (no faces, no foreign brand marks or baked-in text, no watermark, no heavy filters); print quality (sharp, ≥ 1200 px on the long side, exposure holds shadow detail); composition (a usable crop exists for at least one of: wide 16:9 band, 4:5 tall, 1:1 square). Also record: orientation, dominant light colour (warm/cool/mixed), what is depicted in 8 words, and whether it could be mistaken for a product the store sells (yes/no).`
const GATHER = { type: 'object', required: ['downloaded', 'notes'], properties: { downloaded: { type: 'number' }, notes: { type: 'string' } } }
phase('Gather')
const gathered = await parallel([
  () => agent(`Repo ${REPO}. Read ${H}/BRIEF.md §2 (Images). Run the helper ${IMG}/fetch.py (python3) with the sub-command 'openverse' for each of these queries, n=18, one after another, waiting 3 seconds between calls (the API rate-limits): "garden lights night", "garden path lights dusk", "solar lamp garden", "solar garden light", "bollard light garden night", "string lights patio night", "string lights balcony night", "terrace lights evening", "wall lamp night house", "outdoor wall light night", "garden at dusk", "backyard night lights", "led garden lights", "festoon lights garden", "lantern garden night", "steps lights night garden", "mediterranean garden night", "olive tree garden evening". Then run 'python3 ${IMG}/fetch.py own' once (downloads the store's 165 product frames). Report the totals (count lines in ${IMG}/manifest.jsonl before and after). Do not look at the images; do not modify the helper.`, { label: 'gather:openverse+own', phase: 'Gather', schema: GATHER, effort: 'low' }),
  () => agent(`Repo ${REPO}. Read ${H}/BRIEF.md §2 (Images). Run the helper ${IMG}/fetch.py (python3) with the sub-command 'commons' for each of these queries, n=14, one after another with 2 seconds between calls: "garden light night", "garden path lamp night", "solar lamp garden", "string lights terrace night", "balcony lights night", "outdoor wall lamp night", "garden at dusk", "patio evening lights", "festoon lights night", "garden lantern evening", "illuminated garden path", "night garden Israel", "garden lighting", "bollard lamp", "solar powered lamp". Report the totals (count lines in ${IMG}/manifest.jsonl before and after). Do not look at the images; do not modify the helper.`, { label: 'gather:commons', phase: 'Gather', schema: GATHER, effort: 'low' }),
])
log(`gathered: ${gathered.filter(Boolean).map(g => g.downloaded).join(' + ')} files`)

phase('Rate')
const RATE = { type: 'object', required: ['rated', 'keep'], properties: { rated: { type: 'number' }, keep: { type: 'array', items: { type: 'object', required: ['id', 'total', 'depicts', 'crop', 'productLookalike'], properties: { id: { type: 'string' }, total: { type: 'number' }, depicts: { type: 'string' }, crop: { type: 'string' }, productLookalike: { type: 'boolean' } } } } } }
// chunk the manifest ids in plain code: the rating agents each take a slice; the slicing agent lists ids into a file first
const lister = await agent(`Repo ${REPO}. Read ${IMG}/manifest.jsonl and write ${IMG}/chunks.json: a JSON array of arrays, each inner array = up to 22 manifest ids, in manifest order, covering EVERY id exactly once (own_* frames included). Return the number of chunks.`, { label: 'rate:chunks', phase: 'Rate', schema: { type: 'object', required: ['chunks'], properties: { chunks: { type: 'number' } } }, effort: 'low' })
const nChunks = lister ? lister.chunks : 0
const rated = await parallel(Array.from({ length: nChunks }, (_, i) => () => agent(`Repo ${REPO}. You rate photographs for the ElmsNest home page (solar outdoor lighting, night look). Read ${H}/BRIEF.md §2 (Images) and §3. Open ${IMG}/chunks.json and take chunk index ${i} (0-based). For EVERY id in it: find its record in ${IMG}/manifest.jsonl, Read the image file (the Read tool shows it to you; if a file is larger than 4000 px on a side, make a 1600 px copy with PIL into /tmp/claude-0/-home-user-ElmsNest/1c2132db-077d-58e0-b54a-35f2ebea6b2c/scratchpad/rate-${i}/ and Read that). ${RUBRIC} Write one JSON line per image to ${IMG}/ratings.jsonl (append; fields: id, atmosphere, relevance, cleanliness, quality, composition, total (sum), orientation, lightColour, depicts, crop, productLookalike, note) — write as you go so nothing is lost. Return the count rated and the ids with total ≥ 17 in 'keep' (with their depicts/crop/productLookalike). Be strict: a beautiful street festival is not a garden; a product cut-out on white scores 0 on atmosphere.`, { label: `rate:${i}`, phase: 'Rate', schema: RATE, effort: 'medium' })))
const keep = rated.filter(Boolean).flatMap(r => r.keep)
log(`rated ${rated.filter(Boolean).reduce((n, r) => n + r.rated, 0)} images, ${keep.length} at 17+`)

phase('Shortlist')
const SHORT = { type: 'object', required: ['shortlist', 'gaps', 'contactSheet'], properties: { shortlist: { type: 'array', items: { type: 'object', required: ['id', 'role', 'why', 'credit'], properties: { id: { type: 'string' }, role: { type: 'string' }, why: { type: 'string' }, credit: { type: 'string' } } } }, gaps: { type: 'array', items: { type: 'string' } }, contactSheet: { type: 'string' } } }
const short = await agent(`Repo ${REPO}. Read ${H}/BRIEF.md (§2 Images and §3 idea seeds). The raters' picks (total ≥ 17 of 25): ${JSON.stringify(keep)}. Read ${IMG}/ratings.jsonl for the full scores and ${IMG}/manifest.jsonl for source/license/author. Look at every picked image yourself (Read). Build a SHORTLIST of 12–18 images that covers the idea seeds: for each, a role (e.g. 'day-frame', 'night-frame', 'wide band', 'question: sun', 'question: distance', 'question: indoors', 'winter mood', 'light kind: path/wall/beam/string', 'tall portrait', 'square'), why it earns the place, and the credit line it needs («צילום: Author (CC BY 2.0)», or 'none' for CC0/PDM/store-owned). Prefer the store's own frames (own_*) whenever they match a role at similar quality — they are the products themselves and need no credit. Reject duplicates of the same scene. Then write ${IMG}/SHORTLIST.md (a table: id · role · source · license · author · why) and a contact sheet ${IMG}/contact-sheet.html (each shortlisted image at 360 px wide with id, role, license, in a responsive grid, night background) and screenshot it with playwright to ${IMG}/contact-sheet.png (1366 wide, full page; playwright is at /tmp/claude-0/-home-user-ElmsNest/*/scratchpad/node_modules/playwright, chromium at /opt/pw-browsers/chromium-1194/chrome-linux/chrome). List 'gaps': roles for which no candidate scored ≥ 17, so the lead can decide whether to search more or generate.`, { label: 'shortlist', phase: 'Shortlist', schema: SHORT, effort: 'high' })
return { gathered, ratedCount: rated.filter(Boolean).reduce((n, r) => n + r.rated, 0), keepCount: keep.length, shortlist: short }