export const meta = {
  name: 'home2-build',
  description: 'Home round 2: build the winning image-led sections from SPEC.md — one engineer per section, one template engineer, a contract reviewer, a fixer',
  phases: [
    { title: 'Build', detail: 'one engineer per section + the template' },
    { title: 'Review', detail: 'contract reviewer over every new file' },
    { title: 'Fix', detail: 'apply reviewer findings' },
  ],
}
const REPO = '/home/user/ElmsNest', H = `${REPO}/brief/side-pages/home2`, THEME = `${REPO}/theme`, SIM = `${REPO}/brief/side-pages/simplify`
const sections = args && args.sections ? args.sections : []   // [{key, file, specSection}]
const COMMON = `Repo ${REPO}. You build one file of the ElmsNest home round 2. Read first: ${H}/SPEC.md in full (the contract: §1 the sections, §2 copy, §3 images and credits, §4 file rules, §5 acceptance), ${H}/BRIEF.md §2 (the binding constraints), ${SIM}/SPEC.md §2 (P1–P7) and §4 (tokens). Study two existing sections as the house style and copy their conventions exactly: ${THEME}/sections/elmsnest-s-fit.liquid and ${THEME}/sections/elmsnest-s-collections.liquid (schema in Hebrew, settings for every text, <style> block with logical properties, radius 0, bdi isolation of digits/Latin, no JS, reduced-motion rule, section root class env2-section, dir="rtl"). Images are theme assets already in ${THEME}/assets/ (ens-home-*.jpg; sizes in ${H}/images/CHOSEN.md): render an image_picker setting when set, else the asset — e.g. {% if section.settings.image != blank %}{{ section.settings.image | image_url: width: 1600 | image_tag: loading: 'lazy', widths: '600,900,1200,1600', sizes: '(min-width:901px) 50vw, 100vw', alt: '' }}{% else %}<img src="{{ 'ens-home-x.jpg' | asset_img_url: '1600x' }}" srcset="{{ 'ens-home-x.jpg' | asset_img_url: '600x' }} 600w, {{ 'ens-home-x.jpg' | asset_img_url: '900x' }} 900w, {{ 'ens-home-x.jpg' | asset_img_url: '1600x' }} 1600w" sizes="(min-width:901px) 50vw, 100vw" width="1600" height="<the real ratio>" loading="lazy" decoding="async" alt="">{% endif %}. A credit line, when SPEC §3 requires one, is an 11 px muted caption inside the figure («צילום: … (CC BY 2.0)») — never omitted. Hard rules: valid Liquid; the Hebrew copy EXACTLY as SPEC §2 gives it (guillemets are notation); no '"""' anywhere; no url setting with a page-path default; no text setting with an empty default; every digit/Latin token inside Hebrew in <bdi dir="ltr">; schema "name" ≤ 25 chars with the «ElmsNest S — » prefix; a "presets" entry; section height at 390 ≤ the number SPEC §1 gives for it. When done, run 'python3 ${REPO}/brief/lint.py ${THEME}' and fix what it says about your file.`
const BUILD = { type: 'object', required: ['file', 'settings', 'assumptions', 'deviations', 'lint'], properties: { file: { type: 'string' }, settings: { type: 'array', items: { type: 'string' } }, assumptions: { type: 'array', items: { type: 'string' } }, deviations: { type: 'array', items: { type: 'string' } }, lint: { type: 'string' } } }
phase('Build')
const built = await parallel([
  ...sections.map(s => () => agent(`${COMMON}\nYOUR FILE: ${THEME}/sections/${s.file} — SPEC §1 item «${s.key}» (${s.specSection}). Return the file path, the list of schema setting ids, assumptions, deviations, and the lint lines that mention your file.`, { label: `build:${s.key}`, phase: 'Build', schema: BUILD, effort: 'high' })),
  () => agent(`${COMMON}\nYOUR FILE: ${THEME}/templates/index.json — edit the CURRENT file (keep the /* */ header and every existing section untouched). Add the new sections exactly where SPEC §1 places them in "order", with the section ids and settings SPEC §4 lists (the engineers building the sections use the same setting ids — read ${H}/SPEC.md §4 for the ids and defaults; where the spec says a setting is left to the section default, omit it). If SPEC §1 moves the guide link out of the fit block, set "guide_label": "" on ens_fit. Re-parse the JSON after stripping the header (python3). Return the file path, the ids of the sections you added, assumptions, deviations, lint.`, { label: 'build:template', phase: 'Build', schema: BUILD, effort: 'medium' }),
])
const ok = built.filter(Boolean)
log(`built: ${ok.map(b => b.file.replace(THEME + '/', '')).join(', ')}`)

phase('Review')
const REVIEW = { type: 'object', required: ['verdict', 'findings'], properties: { verdict: { type: 'string' }, findings: { type: 'array', items: { type: 'object', required: ['file', 'line', 'severity', 'problem', 'fix'], properties: { file: { type: 'string' }, line: { type: 'integer' }, severity: { type: 'string' }, problem: { type: 'string' }, fix: { type: 'string' } } } } } }
const review = await agent(`Repo ${REPO}. You are the contract reviewer for the home round 2 build. Read ${H}/SPEC.md and ${H}/BRIEF.md §2, then EVERY new/edited file: ${ok.map(b => b.file).join(', ')} (and ${THEME}/assets/ens-home-*.jpg exist? check the names the sections reference against ls). Check: valid Liquid (balanced tags, filters that exist — asset_img_url takes a size string like '900x'; image_url/image_tag on picker images); the copy byte-identical to SPEC §2; every digit/Latin run in Hebrew inside <bdi dir="ltr">; credits present where SPEC §3 requires; no '"""'; schema: name ≤ 25 chars, no url page-path default, no empty text default, presets present, every text/image in the markup backed by a setting; index.json parses and its section ids/types/settings match the section schemas and SPEC §1 order; the fit block's guide link handled per SPEC; images: width/height attributes, lazy, srcset with asset sizes; CSS: logical properties only, radius 0 except pills, reduced-motion rule, no JS; the section's own estimate of height at 390 vs SPEC's cap (reason from the CSS: image aspect × width + paddings + type). Severity: blocker (invalid, contract broken, claim in copy) / high / medium / low. Do not modify files. 4–6 sentence verdict.`, { label: 'review:contract', phase: 'Review', schema: REVIEW, effort: 'high' })
log(`review: ${review ? review.findings.length : 'null'} findings`)

phase('Fix')
const FIXED = { type: 'object', required: ['changed', 'skipped', 'lint'], properties: { changed: { type: 'array', items: { type: 'string' } }, skipped: { type: 'array', items: { type: 'object', required: ['finding', 'reason'], properties: { finding: { type: 'string' }, reason: { type: 'string' } } } }, lint: { type: 'string' } } }
let fixed = null
if (review && review.findings.length) {
  fixed = await agent(`${COMMON}\nYou are the fixer. Apply EVERY finding below to the files under ${THEME} with the smallest edit (Edit tool). Never touch elmsnest-v2-core.liquid, the skin, or any Kalles file; only the new sections and templates/index.json. Re-read after each edit; re-parse index.json. Findings: ${JSON.stringify(review.findings)}. Run lint, paste its last 6 lines. Return files changed and any finding not applied with the reason.`, { label: 'fix:apply', phase: 'Fix', schema: FIXED, effort: 'high' })
}
return { built: ok, review, fixed }
