export const meta = {
  name: 'pages-build',
  description: 'Content pages build: one section rendering all seven handles plus the photo snippet, the two template JSONs and the verifier probes, then three checking lenses before the lead deploys',
  phases: [
    { title: 'Build', detail: 'the section and snippet; the templates and probes' },
    { title: 'Check', detail: 'contract, theme and honesty lenses on the real files' },
  ],
}
const REPO = '/home/user/ElmsNest', P = `${REPO}/brief/side-pages/pages`, P3 = `${REPO}/brief/side-pages/pdp3`, SIM = `${REPO}/brief/side-pages/simplify`
const PW = 'playwright is at /tmp/claude-0/-home-user-ElmsNest/*/scratchpad/node_modules/playwright (resolve the glob with fs.readdirSync), chromium executablePath /opt/pw-browsers/chromium-1194/chrome-linux/chrome with args [--no-sandbox]; fonts: /home/user/ElmsNest/brief/assets/fonts'
const READ = `The contract is ${P}/SPEC.md — read it in full (§1 the rulings and why they stand, §2 the plumbing, §3 the ten photographs with their kickers, captions and credits, §4 the copy changes, §5 the budgets). The copy is ${P}/COPY-SOURCE.md — verbatim, every sentence, every number; change only what SPEC §4 lists. The winning structure is drawn in ${P}/concepts/atlas/ (index.html, NOTES.md, COPY.md) — read it and take its devices; the opening band grammar and its measured contrast are in ${P}/concepts/band/; the guide's places frame with four labels is in ${P}/concepts/quiet/ (index.html + NOTES.md §1); About's signed ending is in ${P}/concepts/letter/. Also read ${SIM}/SPEC.md §2 (P1–P7) and §4 (tokens), ${REPO}/brief/BRIEF.md §3 (honesty), ${REPO}/theme/snippets/elmsnest-v2-core.liquid (the :root tokens — use --env2-* names), ${REPO}/theme/snippets/elmsnest-s-place.liquid (the four licensed pairs and the collection handles), and two built S sections for the house style: ${REPO}/theme/sections/elmsnest-s-pdp-scene.liquid (image markup, srcset loop capped at the file width, the <bdi> token loop, schema shape) and ${REPO}/theme/sections/elmsnest-s-terms.liquid.`
phase('Build')
const BUILT = { type: 'object', required: ['files', 'notes'], properties: { files: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' }, heights: { type: 'string' } } }
const built = await parallel([
  () => agent(`Repo ${REPO}. You write the production section that re-dresses all seven ElmsNest content pages. ${READ}
Write exactly two files:
1. ${REPO}/theme/sections/elmsnest-s-page.liquid — enabled_on templates ["page"], one {% case page.handle %} with the seven branches of SPEC §2 and an else branch printing page.title + page.content as plain prose. Every h1 and lead a schema text setting with the COPY-SOURCE default; the long copy literal Liquid inside its branch; the four collection titles and counts live from collections[handle]; why-solar's does-not-suit rows from elmsnest-s-place; the shipping numbers hard-coded with the shipping_from_body checkbox escape hatch. The devices per page exactly as SPEC §1 R1/R4/R6 and the atlas concept draw them. All CSS inline in the section, scoped to its own classes, tokens by name, radius 0 except the one gold pill, logical properties, no JS beyond native <details>.
2. ${REPO}/theme/snippets/elmsnest-s-page-photo.liquid — the one photograph slot of SPEC §2 (image picker or theme asset, kicker, caption, credit, alt, object-position per breakpoint, band vs inline, h1_on), rendering <figure>/<figcaption> with width, height, loading (eager only for the first band), decoding, sizes and srcset candidates never exceeding the real file width (the ten assets and their real sizes are in ${P}/IMAGES.md).
Then verify: python3 ${REPO}/brief/lint.py theme passes; the schema parses as JSON; every asset name matches a file in ${REPO}/theme/assets/. Do not write any other file — not the templates, not the verifier.
Return the two paths and any deviation from the spec with its reason.`, { label: 'build:section', phase: 'Build', schema: BUILT, effort: 'high' }),
  () => agent(`Repo ${REPO}. You prepare the template swap and the verification for the content-page round. ${READ}
Write exactly these:
1. ${REPO}/theme/templates/page.json — order ["ens_page"] only, section id ens_page of type elmsnest-s-page with empty settings; keep the Shopify auto-generated comment header that the current file has (read it first: the current file is the rollback and must be copied verbatim to ${P}/rollback/page.json before you change it).
2. ${REPO}/theme/templates/page.contact-us.json — order ["ens_page","contact_form"], ens_page first, the existing Kalles contact-form section entry copied byte-identically from the current file (never edited); the current file copied to ${P}/rollback/page.contact-us.json first.
3. Extend ${REPO}/brief/side-pages/simplify/verify-mirror.js: the seven content pages are already in its page table — add a probe object 'pageCopy' that, on any page whose name starts with 'page-', records the h1 text, whether the page's own SPEC §3 caption strings and kickers are present, whether the four live collection titles appear where SPEC §4.1 says, the seven policy numbers (חינם, 29.90, 1–3, 7–14, 8–17, 14, 5%, 100) on the pages that carry them, the count of <h1> elements (must be 1), the number of images with width+height+lazy, and any link with an empty or '#' href. Keep every existing probe working (read the file first, change nothing else, node --check it).
Do not touch the section, the snippet or any asset.
Return the paths written and what the new probe records.`, { label: 'build:plumbing', phase: 'Build', schema: BUILT, effort: 'high' }),
])
log(`built: ${built.filter(Boolean).flatMap(b => b.files).join(' · ')}`)

phase('Check')
const CHECK = { type: 'object', required: ['verdict', 'findings'], properties: { verdict: { type: 'string' }, findings: { type: 'array', items: { type: 'object', required: ['file', 'severity', 'what', 'fix'], properties: { file: { type: 'string' }, severity: { type: 'string' }, what: { type: 'string' }, fix: { type: 'string' } } } } } }
const LENSES = [
  ['copy', `Read ${P}/COPY-SOURCE.md and ${P}/SPEC.md §4, then ${REPO}/theme/sections/elmsnest-s-page.liquid. For EVERY one of the seven pages compare the section's copy against the source sentence by sentence: anything dropped that §4 does not drop, anything reworded, any number changed (the policy numbers must be byte-identical), any missing link or changed href, any <bdi> lost around a digit or Latin token, the four collection titles, the four licensed pairs. List every difference with the source line.`],
  ['theme', `You are the theme engineer. Read ${REPO}/theme/sections/elmsnest-s-page.liquid, ${REPO}/theme/snippets/elmsnest-s-page-photo.liquid, ${REPO}/theme/templates/page.json, ${REPO}/theme/templates/page.contact-us.json and ${P}/SPEC.md §2 and §5. Check: Liquid correctness (undefined variables, filters on nil, whitespace control, the case/when covering all seven handles plus else), the schema parses and every setting has an id and a Hebrew label, CSS scoped with no bleed and no !important, tokens by name, logical properties, radius 0, no JS beyond <details>, every image sized + lazy (except the first band) + sizes + srcset ≤ file width against the real sizes in ${P}/IMAGES.md, the contact template keeping the stock form section byte-identical, the rollback copies present in ${P}/rollback/. Run python3 ${REPO}/brief/lint.py theme and node --check on the verifier and report both.`],
  ['honesty', `You are the brand guardian. Read ${REPO}/brief/BRIEF.md §3, ${P}/SPEC.md §1 (R5, R7, R8) and §3, ${P}/IMAGES.md, and the section file. Check every drawn credit against ${P}/IMAGES.md (CC BY / BY-SA credited exactly, CC0 needing none), every caption carrying its kicker and naming the place or mechanism before anything else, no photograph readable as a store product under a product heading, no claim the store cannot back, no count except products_count, no urgency, no review, and that the numbers equal the policies. Also confirm the Pexels kerosene lantern is gone.`],
]
const checks = await parallel(LENSES.map(([who, role]) => () => agent(`Repo ${REPO}. ${role}\nReturn a verdict sentence and every finding with file, severity (blocker | should | nit), what is wrong and the exact fix. Do not modify any file.`, { label: `check:${who}`, phase: 'Check', schema: CHECK, effort: 'high' })))
return { built: built.filter(Boolean), checks: checks.filter(Boolean) }
