export const meta = {
  name: 'pdp2-build',
  description: 'PDP round 2: build the two sections and the template edit from SPEC.md — one engineer per section, one template engineer, a contract reviewer, a fixer',
  phases: [
    { title: 'Build', detail: 'two section engineers + the template' },
    { title: 'Review', detail: 'contract reviewer over every new file' },
    { title: 'Fix', detail: 'apply reviewer findings' },
  ],
}
const REPO = '/home/user/ElmsNest', P = `${REPO}/brief/side-pages/pdp2`, THEME = `${REPO}/theme`, SIM = `${REPO}/brief/side-pages/simplify`
const COMMON = `Repo ${REPO}. You build one file of the ElmsNest product-page round 2. Read first: ${P}/SPEC.md in full (the contract: §1 the sections and the photograph rule, §2 copy, §3 the assets and the per-product map with crops, §4 file rules, §5 acceptance), ${P}/BRIEF.md §2–§3 (the binding constraints), ${SIM}/SPEC.md §2 (P1–P7) and §4 (tokens). Study the house style and copy its conventions exactly: ${THEME}/sections/elmsnest-s-home-band.liquid (the in-flow full-bleed photograph with asset fallback, srcset from asset_img_url, --ens-op crops, alt handling — reuse its skeleton), ${THEME}/sections/elmsnest-s-pdp-facts.liquid (the hairline rows, the bdi token loop, the schema style), ${THEME}/sections/elmsnest-s-products.liquid (the env2-h heading scale and the related-mode render of elmsnest-s-place), ${THEME}/snippets/elmsnest-s-place.liquid (emit:'word' / 'collection', and the solar gate to copy verbatim — lines 96–108), ${THEME}/snippets/elmsnest-s-pdp-terms-line.liquid (the «לכל התנאים ←» link markup and CSS to mirror for the guide link). The assets exist in ${THEME}/assets/ens-pdp-*.jpg (sizes in ${P}/images/CHOSEN.md — read them for the width/height attributes and the srcset candidates: never a candidate wider than the file). Hard rules: valid Liquid; the Hebrew copy EXACTLY as SPEC §2 gives it (guillemets are notation); no '"""' anywhere; no url setting with a page-path default; no text setting with an empty default (omit the default key); every digit/Latin token inside Hebrew in <bdi dir="ltr">; schema "name" ≤ 25 chars with the «ElmsNest S — » prefix; a "presets" entry; "enabled_on": {"templates": ["product"]}; logical properties only (no left/right/margin-left…); radius 0; no JS; a reduced-motion rule; section heights at 390 within SPEC §1 caps (reason from the CSS). Blocks: an image_picker in a block cannot have a default — the map in Liquid is the default rendering; the blocks are the owner's override. When done, run 'python3 ${REPO}/brief/lint.py ${THEME}' and fix what it says about your file. Do not touch any other file.`
const BUILD = { type: 'object', required: ['file', 'settings', 'assumptions', 'deviations', 'lint'], properties: { file: { type: 'string' }, settings: { type: 'array', items: { type: 'string' } }, assumptions: { type: 'array', items: { type: 'string' } }, deviations: { type: 'array', items: { type: 'string' } }, lint: { type: 'string' } } }
phase('Build')
const built = await parallel([
  () => agent(`${COMMON}\nYOUR FILE: ${THEME}/sections/elmsnest-s-pdp-scene.liquid — SPEC §1 A («ElmsNest S — בלילה»): the photograph rule (owner block → per-product map with the fifteen handles and crops of §3 → no photograph → the scene_fallback option with the four collection pickers, pictured products and the credit line), the text block (place heading by emit:'word' with the birch override, family line by place, the guide link with link_label/link_url), the desktop two-column text block, the credit line's title through a bdi token loop. Return the file path, the list of schema setting ids (settings and block settings), assumptions, deviations, the lint lines that mention your file.`, { label: 'build:scene', phase: 'Build', schema: BUILD, effort: 'high' }),
  () => agent(`${COMMON}\nYOUR FILE: ${THEME}/sections/elmsnest-s-pdp-dusk.liquid — SPEC §1 B («ElmsNest S — כשמחשיך»): the solar gate copied verbatim from elmsnest-s-place (three states: metafield, else title + stripped description contain «סולארי»; prints NOTHING otherwise — not even the section root), the hairline row with the heading and the two sentences, the facts-row grid at ≥ 901, ≤ 160 px at 390. Return the file path, the schema setting ids, assumptions, deviations, the lint lines that mention your file.`, { label: 'build:dusk', phase: 'Build', schema: BUILD, effort: 'high' }),
  () => agent(`${COMMON}\nYOUR FILE: ${THEME}/templates/product.elmsnest.json — edit the CURRENT file (keep the /* */ header and every existing section and block untouched, byte for byte). Add exactly the two entries SPEC §4 gives ("ens_pdp_scene" with settings {"link_url": "shopify://pages/guide-garden-lighting"}; "ens_pdp_dusk" with settings {}) and the new order main-product → ens_pdp_scene → ens_pdp_dusk → ens_pdp_facts → ens_related. Re-parse the JSON after stripping the header (python3). Return the file path, the ids of the sections you added, assumptions, deviations, lint.`, { label: 'build:template', phase: 'Build', schema: BUILD, effort: 'medium' }),
])
const ok = built.filter(Boolean)
log(`built: ${ok.map(b => b.file.replace(THEME + '/', '')).join(', ')}`)

phase('Review')
const REVIEW = { type: 'object', required: ['verdict', 'findings'], properties: { verdict: { type: 'string' }, findings: { type: 'array', items: { type: 'object', required: ['file', 'line', 'severity', 'problem', 'fix'], properties: { file: { type: 'string' }, line: { type: 'integer' }, severity: { type: 'string' }, problem: { type: 'string' }, fix: { type: 'string' } } } } } }
const review = await agent(`Repo ${REPO}. You are the contract reviewer for the product-page round 2 build. Read ${P}/SPEC.md and ${P}/BRIEF.md §2–§3, then EVERY new/edited file: ${ok.map(b => b.file).join(', ')}, and ls ${THEME}/assets/ens-pdp-*.jpg against the names the scene section references (every referenced asset must exist; read ${P}/images/CHOSEN.md for each file's true width/height and check the width/height attributes and srcset candidates never exceed the file). Check: valid Liquid (balanced tags, filters that exist — asset_img_url takes a size string like '900x'; image_url/image_tag on picker images; product settings expose .handle/.title/.url); the copy byte-identical to SPEC §2 per family and per gate; the solar gate byte-identical to elmsnest-s-place's three-state test and applied where SPEC says (dusk: the whole section; scene: nowhere); the per-product map covers exactly the fifteen handles of SPEC §3 with their crops; no photograph on an unmapped product unless scene_fallback is true; the credit line only when the pictured product differs from the page's product; the guide link exactly once with link_label/link_url; every digit/Latin run in Hebrew inside <bdi dir="ltr">; no '"""'; schema: name ≤ 25 chars, enabled_on product, no url page-path default, no empty text default, presets present, every text and image in the markup backed by a setting, image_picker in blocks without defaults; product.elmsnest.json parses and its two new entries and order match SPEC §4 with nothing else changed (diff against git HEAD); CSS: logical properties only, radius 0, reduced-motion rule, no JS, the sticky bar's 78 px never hides required text; heights at 390 within SPEC §1 caps (reason from the CSS: 440 photo + paddings + type). Severity: blocker (invalid, contract broken, claim in copy, another product's photograph by default) / high / medium / low. Do not modify files. 4–6 sentence verdict.`, { label: 'review:contract', phase: 'Review', schema: REVIEW, effort: 'high' })
log(`review: ${review ? review.findings.length : 'null'} findings`)

phase('Fix')
const FIXED = { type: 'object', required: ['changed', 'skipped', 'lint'], properties: { changed: { type: 'array', items: { type: 'string' } }, skipped: { type: 'array', items: { type: 'object', required: ['finding', 'reason'], properties: { finding: { type: 'string' }, reason: { type: 'string' } } } }, lint: { type: 'string' } } }
let fixed = null
if (review && review.findings.length) {
  fixed = await agent(`${COMMON}\nYou are the fixer. Apply EVERY finding below to the files under ${THEME} with the smallest edit (Edit tool). Never touch elmsnest-v2-core.liquid, the skin, elmsnest-s-place, elmsnest-s-pdp-facts, or any Kalles file; only the two new sections and templates/product.elmsnest.json. Re-read after each edit; re-parse the template JSON. Findings: ${JSON.stringify(review.findings)}. Run lint, paste its last 6 lines. Return files changed and any finding not applied with the reason.`, { label: 'fix:apply', phase: 'Fix', schema: FIXED, effort: 'high' })
}
return { built: ok, review, fixed }