export const meta = {
  name: 'pdp3-images',
  description: 'PDP round 3 + content pages: source internet photographs (Openverse + Wikimedia Commons, licence-filtered) with NEW queries — daylight panels, installation, weather, golden-hour gardens, Israeli settings — rate every candidate visually, shortlist with roles and credits',
  phases: [
    { title: 'Gather', detail: 'two sources in parallel, new queries' },
    { title: 'Rate', detail: 'every candidate looked at, scored on the rubric' },
    { title: 'Shortlist', detail: 'merge with the home round pool, roles, credits, contact sheet' },
  ],
}
const REPO = '/home/user/ElmsNest', P = `${REPO}/brief/side-pages/pdp3`, IMG = `${P}/images`, H2 = `${REPO}/brief/side-pages/home2/images`
const RUBRIC = `Rubric (0-5 each): relevance (solar outdoor lighting for an Israeli garden, path, wall, balcony, terrace — or one of this round's seeds: a solar cell/panel in the sun, a stake pushed into soil, hands installing a garden light, rain on a lamp, a Mediterranean garden by day or at golden hour, a dusk sky over a garden or balcony; a Christmas street, a stadium, a city skyline scores 0); cleanliness (no faces — hands or a person from behind are fine —, no foreign brand marks or baked-in text, no watermark, no heavy filters); print quality (sharp, ≥ 1200 px on the long side or a usable detail crop of a bigger file, exposure holds detail); composition (a usable crop exists for at least one of: wide 16:9 band, 4:5 tall, 1:1 square, or a small 3:2 detail); atmosphere (warm and calm — this round WELCOMES daylight, golden hour and dusk, not only night; note the tone). Also record: tone (day / golden / dusk / night), orientation, what is depicted in 8 words, the best crop, and whether it could be mistaken for a product the store sells (a lamp that looks like a shop product = productLookalike true).`
const GATHER = { type: 'object', required: ['downloaded', 'notes'], properties: { downloaded: { type: 'number' }, notes: { type: 'string' } } }
phase('Gather')
const gathered = await parallel([
  () => agent(`Repo ${REPO}. Read ${P}/BRIEF.md §3 and §4. Run the helper ${IMG}/fetch.py (python3) with the sub-command 'openverse' for each of these queries, n=18, one after another, waiting 3 seconds between calls (the API rate-limits): "solar panel close up sun", "solar cell macro", "solar garden light daylight", "solar light stake soil", "garden stake light installation", "hands planting garden soil", "garden lamp rain drops", "rain on lamp", "wet garden light rain", "mediterranean garden noon", "olive tree garden sunlight", "israel garden balcony", "tel aviv balcony evening", "jerusalem stone courtyard", "garden golden hour", "sunset garden wall", "patio dusk warm sky", "terrace evening mediterranean", "outdoor wall lamp house dusk", "path lights dusk garden", "string lights pergola dusk", "wall lamp installation drill", "small solar panel garden", "cypress garden sunset", "courtyard lanterns evening", "bougainvillea wall sun", "desert garden sunset", "balcony plants evening lights", "garden steps sunset", "solar powered lamp closeup". Report the totals (count lines in ${IMG}/manifest.jsonl before and after). Do not look at the images; do not modify the helper.`, { label: 'gather:openverse', phase: 'Gather', schema: GATHER, effort: 'low' }),
  () => agent(`Repo ${REPO}. Read ${P}/BRIEF.md §3 and §4. Run the helper ${IMG}/fetch.py (python3) with the sub-command 'commons' for each of these queries, n=14, one after another with 2 seconds between calls: "solar panel close-up", "photovoltaic cell macro", "solar garden lamp daylight", "solar lamp stake", "garden at golden hour", "Mediterranean garden", "Israel garden", "Tel Aviv balcony", "courtyard evening lamp", "garden path sunset", "olive trees sunlight garden", "rain drops lamp", "outdoor lamp rain", "pergola string lights dusk", "wall lantern house evening", "solar street lamp", "Haifa garden", "cypress garden", "garden terrace evening", "garden lighting installation", "Jerusalem garden evening", "Negev sunset garden". Report the totals (count lines in ${IMG}/manifest.jsonl before and after). Do not look at the images; do not modify the helper.`, { label: 'gather:commons', phase: 'Gather', schema: GATHER, effort: 'low' }),
])
log(`gathered: ${gathered.filter(Boolean).map(g => g.downloaded).join(' + ')} files`)

phase('Rate')
const RATE = { type: 'object', required: ['rated', 'keep'], properties: { rated: { type: 'number' }, keep: { type: 'array', items: { type: 'object', required: ['id', 'total', 'tone', 'depicts', 'crop', 'productLookalike'], properties: { id: { type: 'string' }, total: { type: 'number' }, tone: { type: 'string' }, depicts: { type: 'string' }, crop: { type: 'string' }, productLookalike: { type: 'boolean' } } } } } }
const lister = await agent(`Repo ${REPO}. Read ${IMG}/manifest.jsonl and write ${IMG}/chunks.json: a JSON array of arrays, each inner array = up to 24 manifest ids, in manifest order, covering EVERY id exactly once. Return the number of chunks.`, { label: 'rate:chunks', phase: 'Rate', schema: { type: 'object', required: ['chunks'], properties: { chunks: { type: 'number' } } }, effort: 'low' })
const nChunks = lister ? lister.chunks : 0
const rated = await parallel(Array.from({ length: nChunks }, (_, i) => () => agent(`Repo ${REPO}. You rate photographs for the ElmsNest product page round 3 and the content pages (solar outdoor lighting; this round welcomes daylight and golden hour). Read ${P}/BRIEF.md §2–§4. Open ${IMG}/chunks.json and take chunk index ${i} (0-based). For EVERY id in it: find its record in ${IMG}/manifest.jsonl, Read the image file (the Read tool shows it to you; if a file is larger than 4000 px on a side, make a 1600 px copy with PIL into /tmp/claude-0/-home-user-ElmsNest/1c2132db-077d-58e0-b54a-35f2ebea6b2c/scratchpad/rate3-${i}/ and Read that). ${RUBRIC} Write one JSON line per image to ${IMG}/ratings.jsonl (append; fields: id, relevance, cleanliness, quality, composition, atmosphere, total, tone, orientation, depicts, crop, productLookalike, note). Return the count rated and the ids with total ≥ 16 (with total, tone, depicts, crop, productLookalike). Do not skip an image; do not modify any other file.`, { label: `rate:${i}`, phase: 'Rate', schema: RATE, effort: 'medium' })))
const keep = rated.filter(Boolean).flatMap(r => r.keep)
log(`rated ${rated.filter(Boolean).reduce((n, r) => n + r.rated, 0)} images, ${keep.length} at 16+`)

phase('Shortlist')
const SHORT = { type: 'object', required: ['shortlist', 'gaps', 'contactSheet'], properties: { shortlist: { type: 'array', items: { type: 'object', required: ['id', 'role', 'tone', 'why', 'credit'], properties: { id: { type: 'string' }, role: { type: 'string' }, tone: { type: 'string' }, why: { type: 'string' }, credit: { type: 'string' } } } }, gaps: { type: 'array', items: { type: 'string' } }, contactSheet: { type: 'string' } } }
const short = await agent(`Repo ${REPO}. Read ${P}/BRIEF.md (§2 the different look, §3 seeds, §4 licence and honesty). The raters' picks from this round (total ≥ 16 of 25): ${JSON.stringify(keep)}. Read ${IMG}/ratings.jsonl and ${IMG}/manifest.jsonl (this round's files are under ${IMG}/candidates/). ALSO consider the home round's internet pool: ${H2}/ratings.jsonl and ${H2}/manifest.jsonl (ids not starting with own_; files under ${H2}/candidates/; the 42 rated ≥ 14 include a villa garden at dusk CC BY, a curved path with bollards CC BY, a night patio umbrella CC0, a blue-hour lawn CC0, the Bahá'í gardens in Haifa CC BY-SA, the Acre citadel garden CC BY 2.5, a rooftop pergola with festoons, an apartment balcony with fairy lights). Look at every picked image yourself (Read). Build a SHORTLIST of 18–28 images that covers the seeds with VARIETY of tone: for each, a role (e.g. 'solar cell in sun', 'stake in soil', 'hands installing', 'rain on lamp', 'golden-hour garden wide', 'dusk balcony', 'Mediterranean garden day', 'courtyard evening', 'Israeli setting', 'detail square', 'tall portrait', 'content: guide', 'content: about', 'content: why solar', 'content: contact'), the tone, why it earns the place, and the credit line it needs («צילום: Author (CC BY 2.0)», or 'none' for CC0/PDM). Prefer real photographs over renders, prefer ≥ 1600 px, prefer Israeli or Mediterranean settings, refuse anything that could pass for a product the store sells unless the role names it as such. Write ${IMG}/SHORTLIST.md (table + credit lines + rejected picks with reasons + gaps) and build a contact sheet ${IMG}/contact-sheet.png (PIL, 1366 wide, id + tone + score under each thumbnail, shortlist only). Return the shortlist, the gaps and the contact sheet path.`, { label: 'shortlist', phase: 'Shortlist', schema: SHORT, effort: 'high' })
return { gathered, ratedCount: rated.filter(Boolean).reduce((n, r) => n + r.rated, 0), keepCount: keep.length, shortlist: short }