export const meta = {
  name: 'pdp3-build',
  description: 'PDP round 3 build: two new sections (the weather pair and the cream print) written to theme/, the template order updated, everything self-checked against the spec before the lead deploys',
  phases: [
    { title: 'Build', detail: 'one agent per section, rendered and measured locally' },
    { title: 'Check', detail: 'contract review of both files against the spec and P1-P7' },
  ],
}
const REPO = '/home/user/ElmsNest', P = `${REPO}/brief/side-pages/pdp3`, P2 = `${REPO}/brief/side-pages/pdp2`, SIM = `${REPO}/brief/side-pages/simplify`
const PW = 'playwright is at /tmp/claude-0/-home-user-ElmsNest/*/scratchpad/node_modules/playwright (resolve the glob with fs.readdirSync), chromium executablePath /opt/pw-browsers/chromium-1194/chrome-linux/chrome with args [--no-sandbox]; fonts: /home/user/ElmsNest/brief/assets/fonts (declare @font-face from file:// paths in the harness HTML)'
const COMMON = `Repo ${REPO}. You write ONE production Liquid section for the ElmsNest dev theme (Shopify OS 2.0, Kalles 5.4.2, Hebrew RTL). The contract is ${P}/SPEC.md — read it in full; §1 records why each ruling stands, §5 the budgets. Also read ${REPO}/brief/BRIEF.md §3 (honesty) and ${SIM}/SPEC.md §2 (P1–P7) and §4 (tokens).
Copy the house style from the two sections you sit between — read them completely before writing a line: ${REPO}/theme/sections/elmsnest-s-pdp-scene.liquid (the per-handle asset map, the srcset loop capped at the file width, the <bdi> token loop, the schema shape, the credit line) and ${REPO}/theme/sections/elmsnest-s-pdp-dusk.liquid (the solar gate copied verbatim, the row CSS, the desktop column). Also ${REPO}/theme/sections/elmsnest-s-pdp-facts.liquid (the IP token scan you need for the gate) and ${REPO}/theme/snippets/elmsnest-s-place.liquid (place words) and ${REPO}/theme/snippets/elmsnest-v2-core.liquid (the :root tokens — use the --env2-* names, never a raw colour that is already a token).
Hard rules: no JS, no carousel, no reveal, radius 0, logical properties (inline-start/end, padding-block…), every <img> with width, height, loading="lazy", decoding="async", a sizes attribute matching the rendered width and srcset candidates that never exceed the file's real width (the asset widths are in ${P}/images/CHOSEN.md); digits and Latin inside Hebrew wrapped in <bdi dir="ltr">; every string a schema setting with the spec's default; Hebrew schema labels; enabled_on templates ["product"]; the section must print NOTHING when its gate is closed (no empty wrapper, no stray padding); nothing published anywhere — you only write the file into ${REPO}/theme/sections/.
Verify before you finish: (1) python3 ${REPO}/brief/lint.py theme passes; (2) build a local harness in ${P}/build/<name>/ that inlines your section's markup + CSS with the real assets (file:// paths to ${REPO}/theme/assets/…) for the three archetypes A (solar path light, IP65, gate open, solar pair / place word שביל), B (mains wall light, IP65, gate open, plain pair / place word קיר) and C (solar floodlight, IP67, place word גינה) and measure each rendered section height at 390 with playwright — write the numbers into ${P}/build/<name>/MEASURED.md and keep the screenshots; (3) check the caption and credit colours against their real backgrounds with python3 ${P2}/verify/contrast.py on your screenshots (≥ 4.5:1) and record the ratios. ${PW}. Do not touch any other theme file, any other section, the template JSON, or another agent's folder.`
phase('Build')
const SECTIONS = [
  ['weather', `Write ${REPO}/theme/sections/elmsnest-s-pdp-weather.liquid exactly per SPEC §2 («בחוץ, כל השנה»): the two framed detail tiles (1:1 at 390 in two columns with a 12 px gap, 3:2 at ≥ 901), one line under each tile, then the 12 px muted caption + credit; heading above the pair. Both gates: the IP token scan (IP65/IP66/IP67/IP68 in the product's own description → print; else nothing) and the solar test copied verbatim from elmsnest-s-pdp-dusk (solar → the panel rain tile ens-pdp-rain-panel.jpg; anything else → the stem tile ens-pdp-rain-stem.jpg). The sun tile is ens-pdp-sun-wall.jpg on every product. Settings and defaults exactly as SPEC §2's two tables, plus an image_picker per slot (empty = the asset) and per-breakpoint object_position text settings modelled on elmsnest-s-home-solar. Target ≤ 430 px at 390.`],
  ['print', `Write ${REPO}/theme/sections/elmsnest-s-pdp-print.liquid exactly per SPEC §3 (the cream print): one serif sentence on the night ground, then the cream mat (#efe7d8, 14 px padding, radius 0) holding the photograph (3:2 at 390, 16:9 at ≥ 901, bleeding to the mat's inner edge) with the caption and the credit on the mat under it (11 px, #6b6558 — verify the contrast, adjust the ink token if it fails and say so). The gate: elmsnest-s-place emit:'word' must be non-blank, and the two handles lighted-birch-branches-20-led and rechargeable-telescopic-camping-lantern print nothing. The photograph, the caption and the credit are chosen by the place word from SPEC §3's table (four assets: ens-pdp-print-path/wall/garden/balcony.jpg), each overridable by an image_picker with a caption and credit setting. Target ≤ 420 px at 390.`],
]
const BUILT = { type: 'object', required: ['file', 'bytes', 'heights', 'contrast', 'notes'], properties: { file: { type: 'string' }, bytes: { type: 'number' }, heights: { type: 'object', properties: { A: { type: 'number' }, B: { type: 'number' }, C: { type: 'number' } } }, contrast: { type: 'string' }, notes: { type: 'string' } } }
const built = await parallel(SECTIONS.map(([name, task]) => () => agent(`${COMMON}\n\nYOUR SECTION: ${task}\nReturn the file path, its byte size, the measured heights at 390 for A, B and C, the contrast ratios you measured, and any place where you deviated from the spec (with the reason).`, { label: `build:${name}`, phase: 'Build', schema: BUILT, effort: 'high' })))
log(`built: ${built.filter(Boolean).map(b => `${b.file} ${b.bytes}B`).join(' · ')}`)

phase('Check')
const CHECK = { type: 'object', required: ['verdict', 'findings'], properties: { verdict: { type: 'string' }, findings: { type: 'array', items: { type: 'object', required: ['file', 'severity', 'what', 'fix'], properties: { file: { type: 'string' }, severity: { type: 'string' }, what: { type: 'string' }, fix: { type: 'string' } } } } } }
const LENSES = [
  ['contract', `Read ${P}/SPEC.md and both new files (${REPO}/theme/sections/elmsnest-s-pdp-weather.liquid, elmsnest-s-pdp-print.liquid). Check line by line: every setting and default of §2 and §3 present and byte-identical to the spec's Hebrew; the two gates implemented as specified (the IP token list; the solar test copied verbatim from elmsnest-s-pdp-dusk — diff the two code paths; the place word and the two excluded handles); the assets named exactly as in ${P}/images/CHOSEN.md and never referenced with a width larger than the real file; enabled_on templates ["product"]; nothing printed when a gate is closed. List every deviation.`],
  ['theme', `You are the theme engineer. Read both new files plus ${REPO}/theme/sections/elmsnest-s-pdp-scene.liquid and elmsnest-s-pdp-dusk.liquid and ${REPO}/theme/snippets/elmsnest-v2-core.liquid. Check: Liquid correctness (no undefined variable, no filter on nil, whitespace control, no {% render %} of a missing snippet), CSS scoped to the section's own classes with no bleed and no !important, tokens used by name, logical properties everywhere, radius 0, no JS, images sized + lazy + sizes + srcset ≤ file width, no layout shift, the desktop column matching the dusk row's 152px/minmax pattern where the spec asks, schema JSON valid (parse it), Hebrew labels, and P6 <bdi> on every digit or Latin string. Also run python3 ${REPO}/brief/lint.py theme and report its output.`],
  ['honesty', `You are the brand guardian. Read ${REPO}/brief/BRIEF.md §3, ${P}/BRIEF.md §4, ${P}/SPEC.md §1 (rulings R2, R5, R7, R8) and ${P}/images/CHOSEN.md. For both files: is every drawn credit exactly the licence line CHOSEN.md records (CC BY / BY-SA credited, CC0 not)? Does any caption or heading let a photograph read as the store's product? Is any sentence a claim the store cannot back (weather durability, mounting, hours, lumens)? Does anything repeat what the page already says (the scene's place line, the dusk row's two sentences, the facts, the terms, the not-for line)? Is the mains page free of every solar word and solar image? Look at the harness screenshots in ${P}/build/*/ as well as the code.`],
]
const checks = await parallel(LENSES.map(([who, role]) => () => agent(`Repo ${REPO}. ${role}\nReturn a verdict sentence and every finding with file, severity (blocker | should | nit), what is wrong and the exact fix. Do not modify any file.`, { label: `check:${who}`, phase: 'Check', schema: CHECK, effort: 'high' })))
return { built: built.filter(Boolean), checks: checks.filter(Boolean) }
