export const meta = {
  name: 'simplify-build',
  description: 'Build the SIMPLIFY round: six engineers write the new/edited theme files in parallel, one reviewer checks them against the spec contract, one fixer applies the findings',
  phases: [
    { title: 'Build', detail: 'six engineers, disjoint files' },
    { title: 'Review', detail: 'contract reviewer over every file' },
    { title: 'Fix', detail: 'apply reviewer findings' },
  ],
}
const REPO = 'C:\\Users\\covid\\AppData\\Local\\Temp\\claude\\c--Users-covid-Desktop-claude\\bfa8f647-4fec-44c7-8dd1-7c6bb6aaaf08\\scratchpad\\repo'
const SPEC = REPO + '\\brief\\side-pages\\simplify\\SPEC.md'
const CRIT = REPO + '\\brief\\side-pages\\simplify\\SPEC-CRITIQUE.txt'
const KALLES = 'C:\\Users\\covid\\Desktop\\claude\\ElmsNest Theme'
const THEME = REPO + '\\theme'

const COMMON = `You are building one part of the ElmsNest SIMPLIFY round. Read ${SPEC} in full first (it is the contract; §2 principles, §4 tokens, §5 shared pieces, §10 file rules are binding for every file). ${CRIT} explains why each rule exists — skim the findings that touch your files. Theme files we own live in ${THEME} (write there; Windows paths; UTF-8 without BOM, LF line endings). The stock Kalles 5.4.2 source for reading is ${KALLES} (sections/, snippets/, blocks/, assets/, locales/he.json). Existing env2 files under ${THEME} are the visual reference (tokens in snippets/elmsnest-v2-core.liquid; copy patterns from them, do not render them unless the spec says so).
Hard rules for every file you write: valid Liquid; Hebrew copy exactly as the spec gives it (guillemets «» are notation, never typed); every en-dash range and Latin/number token inside a Hebrew line wrapped in <bdi dir="ltr">; no «וואטסאפ», no wa.me; no counts of sales/reviews; no '"""' sequence anywhere; no '{n}' placeholder inside {{ }}; sections use {% schema %} with "name" ≤ 25 chars, setting ids ≤ 25 chars [a-z0-9_], Hebrew labels ≤ 70 chars, and a "presets" entry; CSS inside a plain <style> tag (never {% stylesheet %}); logical CSS properties (inline-start/end, not left/right — a Sense RTL app flips physical ones); radius 0 except pill buttons; no [data-lamp], no opacity-until-lit, no scroll reveal; prefers-reduced-motion respected. Keep every file under 12 KB. Write files with the Write tool, then re-read each file once and check it parses (balanced {% %}, {{ }}, JSON valid via node -e where relevant). When done, return a short JSON-like summary: files written (path + bytes), the interface you assumed from other engineers' files, and anything you could not do exactly as specified (say why).`

const BUILD_SCHEMA = { type: 'object', properties: {
  files: { type: 'array', items: { type: 'object', properties: { path: { type: 'string' }, bytes: { type: 'integer' }, purpose: { type: 'string' } }, required: ['path', 'bytes', 'purpose'] } },
  assumptions: { type: 'array', items: { type: 'string' } },
  deviations: { type: 'array', items: { type: 'string' } },
}, required: ['files', 'assumptions', 'deviations'] }

const ENGINEERS = [
  { key: 'skin', prompt: `${COMMON}
YOUR FILE: snippets/elmsnest-s-skin.liquid (spec §5.1) — one <style> block dressing the STOCK Kalles components in the night language. Before writing, open in ${KALLES}: snippets/card-product1.liquid, snippets/card-product-media.liquid, snippets/card-price.liquid, snippets/price.liquid, snippets/btn-ultra.liquid, sections/main-collection.liquid (lines 160-230), sections/main-product.liquid (sticky bar lines 37-149), blocks/_product-buy-button.liquid, blocks/_product-variant-picker.liquid, snippets/quantity-selector.liquid, sections/cart-drawer.liquid, assets/base.css (search .hdt-ratio--portrait, hdt-reval-items, .hdt-btn), assets/product-card.css, assets/collection-products.css, assets/hdt-sticky-atc.css — and copy the REAL class names into your selectors. Also read ${THEME}\\snippets\\elmsnest-v2-core.liquid for the tokens and font-family variables it defines (use its custom properties, e.g. the serif/sans variables, gold, ink, hairline) so the skin never hard-codes a font name twice. Cover exactly the items listed in spec §5.1 (cards incl. the forced-visible rule for hdt-reval-items, toolbar hidden, main-product title/price/pills/qty/button/sticky bar + hidden sticky qty + the body padding override, the .elms-sales neutralisation inside <details>, cart-drawer, related grid). Every !important gets a one-line comment naming the Kalles file:line that forces it. Hebrew RTL: use inline-start/end. Max ~300 lines.` },
  { key: 'shared', prompt: `${COMMON}
YOUR FILES: snippets/elmsnest-s-place.liquid (spec §5.2 — inputs collection|product + emit: word|yes|no|collection; the solar gate copied from ${THEME}\\sections\\elmsnest-v2-pdp-fit.liquid lines ~98-112; output is plain text, nothing else, no whitespace leaks: use {%- -%} everywhere and 'echo'), snippets/elmsnest-s-contact.liquid (spec §5.4 — read ${THEME}\\snippets\\elmsnest-v2-photo-url.liquid and elmsnest-v2-pdp-photo-cta.liquid for the mailto body logic; output: one <p class="ens-contact"> with the sentence and the link, hairline underline, 44px tap height; accepts optional product), snippets/elmsnest-s-terms.liquid + sections/elmsnest-s-terms.liquid (spec §5.3 — copy the three rows BYTE-FOR-BYTE from ${THEME}\\templates\\collection.json → sections.coll_terms.blocks (numeral/unit/headline/sub for 0 ₪, 8–17, 14 — open the file and copy, do not retype from memory; drop the photo row), foot links with labels verbatim from ${THEME}\\sections\\elmsnest-v2-coll-terms.liquid line ~335, section root id="env2-terms" and class "ens-terms" with data-env2-terms, heading setting default «שלושה מספרים שכדאי לדעת», mobile ≤ 0.5 screen, Frank Ruhl Libre numerals in gold inside <bdi>). Interface others rely on: {% render 'elmsnest-s-place', product: product, emit: 'yes' %} / collection: collection; {% render 'elmsnest-s-contact', product: product %}; {% render 'elmsnest-s-terms' %}.` },
  { key: 'home', prompt: `${COMMON}
YOUR FILES: sections/elmsnest-s-collections.liquid (spec §6.2), sections/elmsnest-s-products.liquid (spec §6.3 with the 'list' and 'related' modes — §5.5 tells you exactly how to render card-product1 and which CSS assets to load; in 'related' mode resolve the place collection with {% render 'elmsnest-s-place', product: product, emit: 'collection' %} (returns a handle) then collections[handle].products, skip the current product, first 4), sections/elmsnest-s-fit.liquid (spec §6.4 — rows use elmsnest-s-place with emit word/yes/no on each of the four collections in menu order; foot = guide link + {% render 'elmsnest-s-contact' %}), an EDIT of sections/elmsnest-v2-hero.liquid (spec §6.1: add ONE checkbox setting show_card, label «להציג את כרטיס המוצר בהירו», default false, gating the card block INCLUDING its design_mode branch — find it around lines 121-141; change nothing else; keep the file's existing structure), and templates/index.json rewritten per spec §6 (order: env2_hero → ens_collections → ens_products → ens_fit → ens_terms; keep the leading Shopify comment header if present; hero settings exactly as §6.1 lists them, keeping the existing eyebrow, heading_line1/2, product, bg_image_index settings, show_sun_rail; the four collection blocks use the handles תאורת-שביל-סולארית, solar-wall-lights, ספוטים-ופרוז-קטורים-סולאריים, גרילנדות-ותאורה-דקורטיבית in that order, wall object_position 0% 50%). Each collection tile and each fit row carries data-ens-place="{{ collection.handle }}" for the order test. Validate the JSON with node -e 'JSON.parse(...)' after stripping the comment header. The home must render the index ground (the hero already does).` },
  { key: 'coll', prompt: `${COMMON}
YOUR FILES: sections/elmsnest-s-coll-header.liquid (spec §7.1 — renders {% render 'elmsnest-v2-ground-collection' %} first; header photo ~40vh with a veil to #020306; h1; meta line; deck line via elmsnest-s-place emit yes/no with collection: collection; the wrapping FILTER ROW with data-ens-place on each pill (values: 'all' + the four handles) and aria-current on the current one; the native SORT form/select with exactly the four options and the noscript button; settings all_image (image_picker) and all_title (text, default «כל המוצרים»)); sections/elmsnest-s-guide-strip.liquid (spec §7.3); templates/collection.json rewritten per spec §7 (order: ens_coll_header → main-collection → ens_guide_strip; main-collection settings EXACTLY as listed in §7.2, no blocks; keep the leading comment header if present; validate JSON with node after stripping the header). Open ${KALLES}\\sections\\main-collection.liquid schema to confirm every setting id/value you write exists (image_ratio value for 4/5 — check the schema options: it may be 'portrait' or a custom value; use what the schema offers and say which). The collection.url for the sort form: on /collections/all use routes.all_products_collection_url.` },
  { key: 'pdp', prompt: `${COMMON}
YOUR FILES: snippets/elmsnest-s-pdp-kicker.liquid, snippets/elmsnest-s-pdp-unit.liquid, snippets/elmsnest-s-pdp-terms-line.liquid (class ens-terms-line; includes the ≤10-line sticky sync script from spec §8.2.8), snippets/elmsnest-s-pdp-notfor.liquid (spec §8.2.9 — {no} via elmsnest-s-place emit 'no' with product, then {% render 'elmsnest-s-contact', product: product %}), sections/elmsnest-s-pdp-facts.liquid (spec §8.2 item 2 — copy the bullet-derivation from ${THEME}\\sections\\elmsnest-v2-pdp-facts.liquid (the <li> under «פרטים שכדאי לדעת» else the « · » run under «פרטים טכניים»), IP numeral only when an IP code exists, caption = that bullet verbatim, <dl> spec table with <bdi>, then <details><summary>כל מה שכתוב על המוצר</summary>{{ product.description }}</details>; no variant table), and templates/product.elmsnest.json rewritten per spec §8: section key EXACTLY 'main-product' (stock main-product with the static blocks copied from ${REPO}\\brief\\inventory\\theme-src\\templates\\product.elmsnest.json and the settings/blocks/order of §8.1 items 1-9 — the _liquid blocks use "option_type":"liquid" and put the {% render %} call in "text" exactly like the old template did; the noscript select block is its own _liquid block after the picker), then ens_pdp_facts, then ens_related (type elmsnest-s-products, settings source 'related', heading «עוד לאותו מקום»). NEVER write templates/product.json. Open ${KALLES}\\blocks\\_group-product.liquid, _product-buy-button.liquid, _product-variant-picker.liquid, _product-title.liquid, _product-price.liquid, _product-medias.liquid, _liquid.liquid and sections/main-product.liquid schemas to confirm every setting id/value exists. For elmsnest-s-pdp-unit copy the variant:change wiring from ${KALLES}\\snippets\\elmsnest-pdp-unit-price.liquid lines ~40-64 and implement the metres/units parsing of spec §8.2.5 (Liquid: split the option value on 'מ' / ' ' and use plus: 0; money via | money with the price divided by metres — compute in cents with divided_by and round to 2 decimals for display: price_cents / metres → format as X.XX ₪ using divided_by: 100.0 | round: 2). Validate the JSON with node after stripping the comment header.` },
  { key: 'footer', prompt: `${COMMON}
YOUR FILE: sections/footer-group.json — EDIT the current dev-theme body (already in ${THEME}\\sections\\footer-group.json; keep its comment header and every setting you are not told to change). Changes per spec §10: (1) the «קולקציות» column's four link labels become the Shopify collection titles in menu order — תאורת שביל, עמוד וגינה (/collections/תאורת-שביל-סולארית, keep the existing URL-encoded href as it is written in the file) · תאורת קיר (/collections/solar-wall-lights) · ספוטים, פרוז׳קטורים ותאורה ניידת · גרילנדות ותאורה דקורטיבית — find the actual key holding those labels (it may be an HTML string in a text/richtext setting); (2) the photo link text becomes «לשלוח תמונה של המקום» and its href becomes the SAME mailto the store builds: mailto:info@elmsnest.com?subject=<url-encoded «בדיקת התאמה — תמונה של המקום»>&body=<url-encoded «שלום, מצרף/ת תמונה של המקום שרוצים להאיר.»> — read ${THEME}\\snippets\\elmsnest-v2-photo-url.liquid to build the exact encoding (spaces as %20); (3) leave the «תנאי משלוח וביטול» /#env2-terms link as is (the new terms section keeps that id); (4) nothing else changes. Validate JSON with node after stripping the header. Report the exact keys you changed.` },
]

phase('Build')
const built = await parallel(ENGINEERS.map(e => () => agent(e.prompt, { label: `build:${e.key}`, phase: 'Build', schema: BUILD_SCHEMA }).then(r => ({ key: e.key, r }))))
const ok = built.filter(Boolean)
log(`built: ${ok.map(b => b.key).join(', ')}`)

phase('Review')
const REVIEW_SCHEMA = { type: 'object', properties: {
  verdict: { type: 'string' },
  findings: { type: 'array', items: { type: 'object', properties: { file: { type: 'string' }, line: { type: 'integer' }, severity: { type: 'string', description: 'blocker | high | medium | low' }, problem: { type: 'string' }, fix: { type: 'string' } }, required: ['file', 'severity', 'problem', 'fix'] } },
}, required: ['verdict', 'findings'] }
const review = await agent(`You are the contract reviewer for the ElmsNest SIMPLIFY build. Read ${SPEC} in full, then read EVERY file the engineers wrote or edited (list below, all under ${THEME}). Check each against the spec and the hard rules: valid Liquid (balanced tags, no undefined filters, render calls use the exact snippet names and parameter names the spec defines), valid JSON templates (strip the leading /* */ header then JSON.parse via node), schema constraints (name ≤ 25, ids ≤ 25 [a-z0-9_], labels ≤ 70, presets present, no {% stylesheet %}), no '"""', no '{n}' inside {{ }}, Hebrew strings exactly as the spec (byte-compare the terms rows against ${THEME}\\templates\\collection.json baseline copy in ${REPO}\\brief\\side-pages\\simplify\\dev-theme-baseline\\templates__collection.json), <bdi> on ranges and Latin tokens, no WhatsApp, no sales/review counts, cards without buttons, exactly one contact line per page body, terms once on home / none on collection / one line on PDP, data-ens-place attributes present, the four handles in menu order everywhere, main-product section key exactly 'main-product', every Kalles setting id/value present in the corresponding schema in ${KALLES}, and the cross-file interfaces (elmsnest-s-place emit values, elmsnest-s-contact params, elmsnest-s-products source modes) consistent between the file that defines them and the files that call them. Files: ${JSON.stringify(ok.flatMap(b => b.r.files.map(f => f.path)))}. Engineers' own deviations: ${JSON.stringify(ok.map(b => ({ key: b.key, deviations: b.r.deviations, assumptions: b.r.assumptions })))}. Report every defect with file, line, severity and the exact fix. Do not modify files.`, { label: 'review:contract', phase: 'Review', schema: REVIEW_SCHEMA })
log(`review: ${review ? review.findings.length : 'null'} findings`)

phase('Fix')
let fixed = null
if (review && review.findings.length) {
  fixed = await agent(`${COMMON}
You are the fixer. Apply EVERY finding below to the files under ${THEME} with minimal edits (Edit tool; do not rewrite whole files unless a JSON template is invalid). After each edit re-read the file; for JSON templates run node -e to parse after stripping the header. Findings: ${JSON.stringify(review.findings)}. Return the list of files changed and any finding you deliberately did not apply (with the reason).`, { label: 'fix:apply', phase: 'Fix', schema: { type: 'object', properties: { changed: { type: 'array', items: { type: 'string' } }, skipped: { type: 'array', items: { type: 'string' } } }, required: ['changed', 'skipped'] } })
}
return { built: ok, review, fixed }