export const meta = {
  name: 'simplify-contract-review',
  description: 'Contract review of the SIMPLIFY build (22 files) against SPEC.md in six disjoint groups, adversarial confirmation of every finding, one fixer, re-review of what changed',
  phases: [{ title: 'Review', detail: '6 disjoint groups, findings written to disk as found' }, { title: 'Confirm', detail: 'one skeptic per finding, must cite the line' }, { title: 'Fix', detail: 'one fixer, minimal edits, lint + JSON parse' }, { title: 'Re-review', detail: 'interfaces + changed files' }],
}
const REPO = '/home/user/ElmsNest', THEME = `${REPO}/theme`, SIM = `${REPO}/brief/side-pages/simplify`
const SPEC = `${SIM}/SPEC.md`, BASE = `${SIM}/dev-theme-baseline`, KALLES = `${REPO}/brief/inventory/theme-src`, OUT = `${SIM}/review`
const RULES = `HARD RULES (SPEC §2, §10): valid Liquid (balanced tags, only filters Shopify has, every render call names an existing snippet with the parameter names the spec defines); JSON templates valid after stripping the leading /* */ header; schema: section/block name <= 25 chars, setting id <= 25 chars [a-z0-9_], labels <= 70, presets[].name <= 25, every section has presets, {% style %} or <style> never {% stylesheet %}; no '"""' anywhere; no '{n}' placeholder inside {{ }}; _liquid blocks and the s-pdp-* snippets read only product/collection/shop/routes, never section or settings; the four terms rows byte-identical to the coll_terms blocks in ${BASE}/templates__collection.json if that file exists, else to the rows quoted in SPEC §5.3; every en-dash range and every Latin/number token inside a Hebrew line in <bdi dir="ltr">; no WhatsApp in any form (וואטסאפ / ווטסאפ / WhatsApp / wa.me); no reviews, sales or popularity counts, no «הנמכרים ביותר» rendering, no urgency, no 'best'; cards carry no button and no overlay control; exactly one contact line («תמונה של המקום» + one mailto) per page body; terms once on home (strip), none on collection, one line on PDP; data-ens-place attributes present and the four collection handles in menu order everywhere; the main product section key is exactly 'main-product'; every Kalles setting id and value used in a template exists in that section's schema under ${KALLES}; headings carry no terminal period; no '+' and no ';' in storefront Hebrew; text links use the ל־ infinitive; buttons use the stock labels («הוסיפו להזמנה») except the one gold pill «לכל המוצרים». The 31 defects in ${SIM}/SPEC-CRITIQUE.txt were 'resolved' in the spec — check the FILES actually implement each resolution.`
const COMMON = `Repo ${REPO}. Read ${SPEC} in full first (it is the contract; §2 principles, §3 question map, §5-§8 per-file specs, §10 file list and schema constraints). The build was written by six engineers in parallel and has never been reviewed. Do not modify any file. ${RULES}
Write findings to disk AS YOU FIND THEM (this container restarts every hour or two): append each finding as one JSON line to ${OUT}/<group>.jsonl with keys file, line, severity (blocker|major|minor), rule, defect, fix (the exact edit). FIRST: if ${OUT}/<group>.jsonl already exists, read it, keep its findings, and continue from where it stops. Run 'python3 ${REPO}/brief/lint.py ${THEME}' once and treat only its schema/'"""'/'{n}' checks as binding — its collection/PDP template rules are from the previous (rejected) round and are being retired.`
const GROUPS = [
  { key: 'home', files: ['snippets/elmsnest-s-skin.liquid', 'snippets/elmsnest-s-place.liquid', 'snippets/elmsnest-s-contact.liquid', 'snippets/elmsnest-s-terms.liquid', 'sections/elmsnest-s-terms.liquid', 'sections/elmsnest-s-collections.liquid', 'sections/elmsnest-s-fit.liquid'], spec: '§5.1-§5.4 and §6' },
  { key: 'pdp', files: ['snippets/elmsnest-s-pdp-kicker.liquid', 'snippets/elmsnest-s-pdp-unit.liquid', 'snippets/elmsnest-s-pdp-terms-line.liquid', 'snippets/elmsnest-s-pdp-notfor.liquid', 'sections/elmsnest-s-pdp-facts.liquid'], spec: '§8' },
  { key: 'collection', files: ['sections/elmsnest-s-coll-header.liquid', 'sections/elmsnest-s-guide-strip.liquid', 'sections/elmsnest-s-products.liquid'], spec: '§7 and §6 (products section serves home featured + PDP related)' },
  { key: 'templates', files: ['templates/index.json', 'templates/collection.json', 'templates/product.elmsnest.json'], spec: '§6, §7, §8 (section keys, block orders, every setting id/value against the schema of the section it configures — Kalles sections main-product / main-collection under ' + KALLES + ', ours under ' + THEME + ')' },
  { key: 'edited', files: ['sections/elmsnest-v2-hero.liquid', 'layout/theme.liquid', 'config/settings_data.json', 'sections/footer-group.json'], spec: '§10 "Edited": diff each against its copy in ' + BASE + ' (files named path__name) — the diff must be EXACTLY the edit the spec names and nothing else; report any other difference as a blocker' },
  { key: 'interfaces', files: ['snippets/elmsnest-s-place.liquid', 'snippets/elmsnest-s-contact.liquid', 'sections/elmsnest-s-products.liquid', 'sections/elmsnest-s-collections.liquid', 'sections/elmsnest-s-fit.liquid', 'sections/elmsnest-s-coll-header.liquid', 'sections/elmsnest-s-guide-strip.liquid', 'snippets/elmsnest-s-pdp-notfor.liquid', 'sections/elmsnest-s-pdp-facts.liquid', 'templates/index.json', 'templates/collection.json', 'templates/product.elmsnest.json', 'sections/footer-group.json', 'sections/header-group.json'], spec: 'the CROSS-FILE contracts only: elmsnest-s-place emit values vs every caller; elmsnest-s-contact parameters vs every caller; elmsnest-s-products source modes vs both templates; data-ens-place present and the four handles in the SAME order in header menu, home tiles, hero lead, collection filter row, footer; the question map §3 (each question answered exactly once per page: count contact lines, terms, place words per template by reading what each section renders); P7 nothing deleted' },
]
const FINDINGS = { type: 'object', required: ['group', 'findings', 'filesRead'], properties: { group: { type: 'string' }, filesRead: { type: 'array', items: { type: 'string' } }, findings: { type: 'array', items: { type: 'object', required: ['file', 'line', 'severity', 'rule', 'defect', 'fix'], properties: { file: { type: 'string' }, line: { type: 'number' }, severity: { type: 'string' }, rule: { type: 'string' }, defect: { type: 'string' }, fix: { type: 'string' } } } }, clean: { type: 'array', items: { type: 'string' } } } }

phase('Review')
const reviews = await parallel(GROUPS.map(g => () => agent(`${COMMON}
You are the ${g.key} reviewer. Your files (under ${THEME}): ${g.files.join(', ')}. Spec sections that bind them: ${g.spec}. Read every one of your files completely, line by line, against the spec and the rules. For Liquid files also check: every {% if %}/{% for %}/{% case %}/{% capture %}/{% unless %} is closed; every {% render 'x' %} names a snippet that exists under ${THEME}/snippets or ${KALLES}/snippets; filters are real Liquid/Shopify filters; schema JSON parses. Report every defect with file, line, severity and the exact fix; also list what you checked and found clean. Group key for the jsonl file: "${g.key}".`, { label: `review:${g.key}`, phase: 'Review', schema: FINDINGS, effort: 'high' })))
const rok = reviews.filter(Boolean)
const all = rok.flatMap(r => r.findings.map(f => ({ ...f, group: r.group })))
log(`review: ${rok.length}/6 groups returned, ${all.length} findings (${all.filter(f => f.severity === 'blocker').length} blockers)`)

phase('Confirm')
const VERDICT = { type: 'object', required: ['verdict', 'evidence'], properties: { verdict: { type: 'string', enum: ['confirmed', 'refuted', 'unverifiable'] }, evidence: { type: 'string' }, betterFix: { type: 'string' } } }
const judged = await parallel(all.map((f, i) => () => agent(`Repo ${REPO}. A reviewer reported this defect in the ElmsNest SIMPLIFY build: ${JSON.stringify(f)}. Contract: ${SPEC} (read the section the finding cites) and these rules: ${RULES}
Open ${THEME}/${f.file} at the cited line and around it. Your job is to REFUTE it if you can: quote the exact line(s) that prove the finding wrong (e.g. the tag IS closed, the snippet DOES exist, the string IS byte-identical, the spec says otherwise). If you cannot refute it AND you can reproduce it by reading the file, return confirmed with the quoted evidence. If you can neither refute nor reproduce (missing file, ambiguous spec), return unverifiable and say why. If the proposed fix is wrong or would break something else, say so in betterFix. Do not modify files.`, { label: `confirm:${f.group}:${i}`, phase: 'Confirm', schema: VERDICT, effort: 'high' }).then(v => ({ ...f, verdict: v ? v.verdict : 'unverifiable', evidence: v ? v.evidence : 'skeptic died', betterFix: v ? v.betterFix : undefined }))))
const keep = judged.filter(f => f.verdict !== 'refuted')
log(`confirm: ${judged.filter(f => f.verdict === 'confirmed').length} confirmed, ${judged.filter(f => f.verdict === 'refuted').length} refuted, ${judged.filter(f => f.verdict === 'unverifiable').length} unverifiable`)

phase('Fix')
const FIXED = { type: 'object', required: ['changed', 'skipped', 'lint'], properties: { changed: { type: 'array', items: { type: 'string' } }, skipped: { type: 'array', items: { type: 'object', required: ['finding', 'reason'], properties: { finding: { type: 'string' }, reason: { type: 'string' } } } }, lint: { type: 'string' } } }
let fixed = null
if (keep.length) {
  fixed = await agent(`Repo ${REPO}. You are the fixer for the ElmsNest SIMPLIFY build. Contract: ${SPEC}; rules: ${RULES}
Apply EVERY confirmed or unverifiable finding below to the files under ${THEME} with the smallest edit that resolves it (Edit tool; never rewrite a whole file unless a JSON template does not parse). Where 'betterFix' is given, prefer it over 'fix'. After each edit re-read the changed region. For JSON templates strip the leading /* */ header and JSON.parse with node after every edit. When done run 'python3 ${REPO}/brief/lint.py ${THEME}' and paste its last 12 lines into 'lint' (the collection/PDP template rules in it are from the rejected round — ignore those; every other line must be clean). Write a running log to ${OUT}/fix-log.md as you go (this container restarts; if the log exists, read it first and skip what is already applied). Findings: ${JSON.stringify(keep)}. Return the files changed and every finding you deliberately did not apply, with the reason.`, { label: 'fix:apply', phase: 'Fix', schema: FIXED, effort: 'high' })
  log(`fix: changed ${fixed ? fixed.changed.length : 0} files, skipped ${fixed ? fixed.skipped.length : 0}`)
}

phase('Re-review')
const changed = fixed ? fixed.changed : []
const rereview = await agent(`${COMMON}
You are the re-reviewer. The fixer changed these files: ${JSON.stringify(changed)} to resolve these findings: ${JSON.stringify(keep.map(f => ({ file: f.file, line: f.line, defect: f.defect })))}. (1) Re-read every changed file completely and check the fix is applied, is minimal, and introduced nothing new (balanced tags, valid JSON, schema constraints, no '"""'). (2) Re-run the INTERFACES check across the whole build: elmsnest-s-place emit values vs callers, elmsnest-s-contact params vs callers, elmsnest-s-products source modes vs both templates, the four handles in menu order in header-group.json / home tiles / hero lead / collection filter row / footer-group.json, and the §3 question map per template. Group key: "rereview". Report remaining defects with exact fixes, and state plainly whether the build is ready to deploy.`, { label: 'rereview', phase: 'Re-review', schema: FINDINGS, effort: 'high' })
return { groups: rok.map(r => ({ group: r.group, findings: r.findings.length, filesRead: r.filesRead.length })), findings: judged, fixed, rereview }
